  const KEY = 'o-toki-fortschritt-v1';
  const GOALS = [20, 40, 60, 100];
  // Wie lang eine Runde ist. Nicht nur abschneiden: eine lange Runde holt
  // wirklich mehr Sätze aus der Lektion, eine kurze lässt Beiwerk weg.
  const SIZE_LABELS = { kurz: 'sizeShort', mittel: 'sizeMedium', lang: 'sizeLong' };
  const SIZES = [
    { id: 'kurz', words: 1, builds: 2, reads: 1, cap: 6 },
    { id: 'mittel', words: 2, builds: 3, reads: 2, cap: 12 },
    { id: 'lang', words: 3, builds: 5, reads: 4, cap: 20 },
  ];
  // Die beiden Sprecherinnen — hier oben, weil der geladene Zustand dagegen
  // geprüft wird.
  // „ilo“ überspringt die Aufnahmen und nimmt die Stimme des Geräts — der
  // Ausweg, wenn die mitgelieferten Dateien auf einem Gerät stumm bleiben.
  const VOICES = [{ id: 'kalaasi' }, { id: 'jlakuse' }, { id: 'ante' }, { id: 'ilo' }];

  // Alles, was die Oberfläche sagt, steht hier — die Lektionen selbst kommen
  // aus den Kursdaten, die in derselben Sprache vorliegen.
  const T = {
    de: {
      level: 'Stufe', xpToday: (a, b) => `${a}/${b} XP heute`, days: 'Tage',
      goalMet: (xp) => `${xp} XP heute · geschafft`,
      levelNext: (xp) => `Noch ${xp} XP bis zur nächsten Stufe`,
      levelLine: (lvl, xp) => `Stufe ${lvl} · noch ${xp} XP bis zur nächsten`,
      greeting: 'o kama pona!',
      introFirst: 'Erst der Satzbau, dann der Wortschatz. Du baust Sätze, statt Vokabeln abzuhaken.',
      introBack: (title) => `Weiter bei „${title}“.`,
      dueCards: (n) => `${n} ${n === 1 ? 'Karte' : 'Karten'} fällig`,
      dueSub: 'wörter, sätze und umschreibungen von vorher',
      concepts: 'konzepte',
      askWord: 'was heißt das wort?', askMeaning: 'was bedeutet der satz?',
      askBuild: 'bau den satz', askFix: 'hier stimmt ein wort nicht — tipp es an',
      askCompound: 'dafür gibt es kein wort — wie sagst du es?',
      askGlyph: 'welches wort ist das?', askFree: 'schreib es selbst — freie eingabe',
      askRule: 'so ist ein satz gebaut',
      hintFix: 'Ein Wort steht zu viel oder fehlt an dieser Stelle.',
      hintBuild: 'Antippen nimmt ein Wort zurück, Ziehen sortiert um.',
      hintFree: 'Der Parser prüft den Satzbau, während du tippst. Andere Wortwahl als '
        + 'die Musterlösung ist in Ordnung, solange die Grammatik stimmt.',
      check: 'Prüfen', next: 'Weiter', understood: 'Verstanden', again: 'Nochmal üben',
      good: 'pona!', notYet: 'Nicht ganz', almost: 'Fast',
      yourSentence: 'dein satz', modelSentence: 'so ist sie gebaut',
      variantRight: 'Richtig — andere Wortwahl, gleiche Aussage',
      lookupOpen: 'Wörter nachschlagen', lookupClose: 'nachschlagen zu',
      lookupSearch: 'Bedeutung oder Wort suchen',
      lookupNone: 'Nichts gefunden.',
      lookupTake: 'antippen setzt das Wort ein',
      particleMissing: (word, help) => `Es fehlt ${word} — ${help}`,
      particleExtra: (word, help) => `${word} ist hier zu viel — ${help}`,
      orderRight: 'Richtig — Beifügungen darfst du umstellen',
      orderNote: 'Beifügungen wirken der Reihe nach. Üblich ist die Reihenfolge unten — '
        + 'sie hält feste Fügungen zusammen.',
      orderWrong: 'Alle Wörter stimmen — in dieser Stellung sagen sie aber etwas anderes.',
      model: 'Musterlösung:', comesBack: 'Kommt in einer der nächsten Wiederholungen zurück.',
      structureOk: '✓ Satzbau in Ordnung', structureLive: '✓ Satzbau in Ordnung',
      missing: (words) => `Satzbau stimmt, aber es fehlt: ${words}`,
      covers: (word, list) => `<b>${word}</b> deckt: ${list}.`,
      literally: (tp, literal) => `<b>${tp}</b> — wörtlich: ${literal}.`,
      glyphIs: (word, list) => `ist <b>${word}</b> — ${list}.`,
      reviewDone: 'Wiederholung geschafft',
      reviewNote: 'Die Karten kommen wieder, wenn es Zeit dafür ist.',
      cards: 'karten', words: 'wörter', correct: 'richtig', xp: 'xp',
      search: 'Wort oder Bedeutung suchen …',
      sandboxTitle: 'o toki!',
      sandboxIntro: 'Schreib irgendetwas auf toki pona. Der Parser zerlegt es und sagt dir, '
        + 'was er sieht — oder was nicht stimmt.',
      sandboxQuestion: ' — eine Frage', sandboxTry: 'Probier:',
      sitelenHint: 'Die Zeichenschrift: ein Zeichen je Wort. Angeschaltet kommt in '
        + 'jeder Lektion eine Zeichenaufgabe dazu, und die Zeichen wandern in die '
        + 'Wiederholung. Der Kurs selbst bleibt unverändert.',
      sitelenOn: 'Zeichen dazulernen', sitelenOff: 'Zeichen abschalten',
      backupTitle: 'fortschritt sichern',
      backupState: (summary) => `Dein Stand liegt nur auf diesem Gerät: ${summary}. `
        + 'Safari räumt ihn nach sieben Tagen ohne Besuch weg — als Homescreen-App nicht.',
      backupSave: 'Sichern', backupLoad: 'Wiederherstellen',
      backupFile: 'Als Datei sichern oder teilen', backupCopy: 'Code in die Zwischenablage',
      backupCopied: 'Kopiert. Sicher ihn dir irgendwo, wo er nicht verlorengeht.',
      backupCopyFailed: 'Kopieren ging nicht — nimm die Datei.',
      backupPick: 'Sicherungsdatei wählen', backupPaste: '… oder Code hier einfügen',
      backupUnreadable: 'Das ist kein lesbarer Sicherungstext.',
      backupForeign: 'Darin steckt kein Fortschritt dieser App.',
      backupUnreadableFile: 'Datei ließ sich nicht lesen.',
      backupFound: (found, exported, now) => `Gefunden: ${found}`
        + `${exported ? ` · gesichert am ${exported}` : ''}.<br>Ersetzt deinen jetzigen Stand: ${now}.`,
      backupApply: 'Diesen Stand übernehmen',
      summary: (lvl, lessons, cards, xp) => `Stufe ${lvl}, ${lessons} Lektionen, ${cards} Karten, ${xp} XP`,
      langLabel: 'sprache', langOther: 'English',
      askTrace: 'zeichne das zeichen',
      traceClear: 'nochmal',
      traceHint: 'Fahr mit dem Finger über die Vorlage. Mehrere Striche sind erlaubt.',
      traceThin: 'Da fehlt noch ein Stück der Vorlage.',
      traceWide: 'Zu viel daneben — bleib auf der Linie.',
      traceScore: (hit, clean) => `Vorlage ${hit}% getroffen, ${clean}% deiner Linie sitzt drauf.`,
      cancel: 'Abbrechen',
      tileHelp: (word) => `${word} — antippen entfernt, ziehen oder Pfeiltasten sortieren um`,
      sentenceLabel: 'Satz',
      pageTitle: 'o toki! — toki pona lernen',
      askCoin: 'sag es ohne eigenes wort',
      coinHint: 'Es gibt kein Wort dafür. Bau eins aus den Wörtern, die es gibt — '
        + 'zwei oder drei reichen.',
      coinGood: 'Geht — so kann man das sagen',
      coinExact: 'Genau die geläufige Fassung',
      coinUsual: (tp, lit) => `Eine geläufige Fassung ist <code>${tp}</code> — wörtlich ${lit}.`,
      coinThin: 'Ein Wort allein umschreibt noch nichts.',
      unknownWords: (list) => `Kein toki-pona-Wort: ${list}`,
      coinBroken: 'Als Wortgruppe geht das noch nicht auf.',
      askStyle: 'welcher satz sagt das?',
      styleTitle: 'nasin ante — mehrere wege',
      styleHint: 'Beide Sätze sind richtig. Der Unterschied liegt in der Absicht.',
      askSyllable: 'bau das wort aus silben',
      syllableBack: (part) => `Silbe ${part} — antippen nimmt sie zurück`,
      syllableHint: 'Jede Silbe hat die Form (K)V(n) — mehr Formen gibt es nicht.',
      syllableWord: (word, sense) => `${word} — ${sense}`,
      voiceTitle: 'kalama — gesprochene wörter',
      voiceHint: 'Alle 137 Wörter sind zweimal aufgenommen, von kala Asi und von '
        + 'jan Lakuse (Projekt Linku). Die App nimmt eine echte Aufnahme, wo es '
        + 'eine gibt, und die Gerätestimme nur für ganze Sätze.',
      voiceNames: { kalaasi: 'kala Asi', jlakuse: 'jan Lakuse', ante: 'abwechselnd',
                    ilo: 'Gerätestimme' },
      voiceFetch: 'für unterwegs holen', voiceFetching: (n, all) => `holt … ${n}/${all}`,
      voiceReady: 'liegen auf dem Gerät', voiceFailed: 'Holen ging nicht.',
      voiceCredit: 'Aufnahmen: kala Asi (CC BY-SA 4.0) und jan Lakuse · Projekt Linku',
      recTitle: 'eigene aufnahmen',
      recHint: 'Die App spricht mit der Stimme deines Geräts. Nimm ein Wort '
        + 'selbst auf, und sie nimmt deine — überall dort, wo ♪ steht.',
      recStart: 'aufnehmen', recStop: 'fertig', recBusy: '● läuft',
      recCount: (n) => `${n} eigene Aufnahme(n)`,
      recDrop: 'alle löschen',
      recDenied: 'Kein Zugriff aufs Mikrofon.',
      recNone: 'Dieses Gerät nimmt nichts auf.',
      recSaved: (word) => `„${word}“ aufgenommen`,
      cardMake: 'Satzkarte', cardShare: 'teilen', cardSave: 'sichern',
      cardFailed: 'Das Bild ließ sich nicht bauen.',
      mapTitle: 'nimi ale — die ganze sprache',
      mapHint: 'Jedes Kästchen ein Wort. Es färbt sich, sobald du es siehst, '
        + 'und wird golden, wenn es sitzt.',
      mapCount: (known, all) => `${known} von ${all} begegnet`,
      mapFirm: (n) => `${n} sitzen fest`,
      mapLegend: ['unbekannt', 'gesehen', 'geübt', 'sitzt'],
      netOpen: (word) => `Wortverband zu ${word} zeigen`,
      netAsHead: 'als Kopfwort', netAsMod: 'als Beifügung',
      netNone: 'Dazu steht im Korpus noch keine Verbindung.',
      netHint: 'Wortverbände aus allen Sätzen der App — so wird toki pona '
        + 'wirklich zusammengesetzt.',
      nameTitle: 'nimi sina — dein name auf toki pona',
      nameHint: 'toki pona kennt vierzehn Buchstaben und nur Silben aus '
        + '(K)V(n). Fremde Namen werden deshalb nicht übersetzt, sondern '
        + 'nachgesprochen — und stehen immer hinter einem Kopfwort.',
      namePlaceholder: 'Name oder Fremdwort',
      nameHeads: { jan: 'Mensch', ma: 'Ort', toki: 'Sprache', ilo: 'Ding' },
      nameEmpty: 'Schreib etwas hinein.',
      phraseTitle: 'toki lon — Sätze für draußen',
      phraseHint: 'Was man wirklich sagt. Tipp ein Wort an, um es nachzuschlagen.',
      phrasePractice: 'Alltagssätze üben',
      phraseLiteral: 'wörtlich',
      skip: 'überspringen',
      skipNote: 'Übersprungen — kommt gleich wieder.',
      readTitle: 'lipu — lesen',
      readHint: 'Zusammenhängende Texte. Tipp auf eine Zeile, dann steht die '
        + 'Übersetzung da; erst raten lohnt sich.',
      readReveal: 'Übersetzung',
      readAll: 'ganzen Text vorlesen', readStop: 'still',
      readShowAll: 'alle Übersetzungen', readHideAll: 'wieder zudecken',
      readCount: (done, all) => `${done} von ${all} gelesen`,
      readLocked: (stage) => `ab Lektion ${stage}`,
      readQuestions: 'Fragen zum Text',
      readBack: 'zurück',
      askQuiz: 'zum text',
      askJoin: 'mach einen satz daraus',
      joinParts: 'aus:',
      joinLa: '<b>la</b> stellt den Rahmen voran: erst der Rahmen, dann <b>la</b>, dann der Satz.',
      joinPi: '<b>pi</b> gruppiert um: alles hinter <b>pi</b> gehört zusammen zum Kopfwort davor.',
      weekTitle: 'diese woche',
      weekDays: ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'],
      weekSum: (xp, days) => `${xp} XP in sieben Tagen · ${days} Tag(e) am Ziel`,
      goalTitle: 'tagesziel',
      goalHint: 'Wie viel willst du dir an einem Tag vornehmen? Eine Aufgabe bringt zehn Punkte.',
      goalPick: (xp) => `${xp} XP`,
      askAnswer: 'antworte frei',
      answerHint: 'Deine Antwort, dein Satz. Geprüft wird der Bau.',
      answerNeeds: (what) => `Die Antwort braucht ${what}.`,
      answerMissing: (what) => `Da fehlt noch ${what}.`,
      answerEcho: 'Das ist die Frage selbst — antworte darauf.',
      answerFree: 'Richtig gebaut — und deine eigene Antwort',
      answerAlso: 'So hätten es andere gesagt:',
      answerEmpty: 'Ein Wort reicht noch nicht.',
      listen: 'anhören', listenAgain: 'nochmal hören',
      askListen: 'was hörst du?',
      askDictation: 'schreib, was du hörst',
      dictationHint: 'Erst hören, dann tippen. Der Knopf spielt es nochmal.',
      dictationRight: 'Wort für Wort getroffen',
      soundTitle: 'aussprache',
      soundHint: 'toki pona wird gesprochen, wie es dasteht: fünf Vokale, keine Dehnung, '
        + 'Betonung immer auf der ersten Silbe. Einzelne Wörter kommen von kala Asi '
        + '(Projekt Linku, CC BY-SA), ganze Sätze von der Stimme deines Geräts. '
        + 'Angeschaltet kommt in jeder Lektion eine Höraufgabe dazu.',
      soundOn: 'Aussprache anschalten', soundOff: 'Aussprache abschalten',
      soundNone: 'Dieses Gerät bringt keine Sprachausgabe mit.',
      soundFailed: 'Hier kommt kein Ton heraus.',
      soundSwitch: 'Bleibt es beim Antippen still, liegt es meist am Gerät: '
        + 'iPhones schalten mit dem Stummschalter auch die Aufnahmen ab. '
        + 'Unter kalama steht „Gerätestimme“ — die spricht dann statt der Dateien.',
      musiTitle: 'utala musi',
      musiLead: 'Sticheln, kontern, Frieden schließen — mit 137 Wörtern und ohne ein '
        + 'einziges Schimpfwort.',
      musiStart: 'utala anfangen',
      musiForgeTitle: 'nimi sin — frisch gebaut',
      musiForgeHint: 'Ein Muster, viele Füllungen. Der Parser prüft jeden Wurf, '
        + 'bevor er hier steht.',
      musiForge: 'Noch einen', musiPattern: 'Muster',
      musiSting: 'Frechheit', musiLiteral: 'wörtlich',
      musiSection: (name, count) => `${name} · ${count}`,
      musiPeace: 'Und danach: <i>mi musi taso</i> — war nur Spaß.',
      sizeTitle: 'länge einer runde',
      sizeHint: 'Wie viele Aufgaben eine Lektion hat. Kurz reicht für die Bahn, '
        + 'lang für den Abend. Wiederholungen richten sich mit.',
      sizeShort: 'Kurz · 6', sizeMedium: 'Mittel · 12', sizeLong: 'Lang · 20',
      weakTitle: 'schwachstellen üben',
      weakSub: (n) => `${n} ${n === 1 ? 'Sache sitzt' : 'Sachen sitzen'} noch nicht`,
      weakDone: 'Schwachstellen durch',
      weakNote: 'Was hier wieder wackelt, steht beim nächsten Mal erneut da.',
      diaryTitle: 'o sitelen — tagebuch',
      diaryHint: 'Ein Satz am Tag, selbst geschrieben. Der Parser liest mit, '
        + 'bewertet aber nicht — es ist dein Tagebuch.',
      diaryOpen: 'Heute schreiben', diaryBack: 'Zurück',
      diaryLead: 'Schreib auf, wie dein Tag war. Kurz reicht.',
      diaryPrompt: 'Anstoß für heute',
      diaryPlaceholder: 'tenpo suno ni la mi …',
      diarySave: 'Eintrag sichern', diarySaved: 'Gesichert.',
      diaryEmpty: 'Noch kein Eintrag. Der erste ist der schwerste.',
      diaryCount: (n, days) => `${n} ${n === 1 ? 'Eintrag' : 'Einträge'}`
        + `${days > 1 ? ` · ${days} Tage am Stück` : ''}`,
      diaryToday: 'heute', diaryXray: 'Satzbau ansehen',
      diaryReward: 'Erster Eintrag heute · +15 XP',
      diaryLines: (ok, all) => `${ok}/${all} Sätze gehen glatt durch`,
      updateReady: 'Neue Fassung ist da.', updateLoad: 'Jetzt laden',
      versionLabel: (v) => `Fassung ${v}`,
      credit: (link) => `Prototyp. Übungssätze aus ${link} (MIT, © 2020 /dev/urandom `
        + 'und Mitwirkende), geprüft von TokiPonaKit.',
    },
    en: {
      level: 'Level', xpToday: (a, b) => `${a}/${b} XP today`, days: 'days',
      goalMet: (xp) => `${xp} XP today · done`,
      levelNext: (xp) => `${xp} XP to go until the next level`,
      levelLine: (lvl, xp) => `Level ${lvl} · ${xp} XP to the next one`,
      greeting: 'o kama pona!',
      introFirst: 'Structure first, vocabulary after. You build sentences instead of ticking off words.',
      introBack: (title) => `Continue with “${title}”.`,
      dueCards: (n) => `${n} ${n === 1 ? 'card' : 'cards'} due`,
      dueSub: 'words, sentences and paraphrases from before',
      concepts: 'concepts',
      askWord: 'what does this word mean?', askMeaning: 'what does this sentence mean?',
      askBuild: 'build the sentence', askFix: 'one word is wrong — tap it',
      askCompound: 'there is no word for this — how do you say it?',
      askGlyph: 'which word is this?', askFree: 'write it yourself — free input',
      askRule: 'this is how a sentence is built',
      hintFix: 'One word is too many or wrong in this spot.',
      hintBuild: 'Tap to take a word back, drag to reorder.',
      hintFree: 'The parser checks the structure as you type. A different word choice than '
        + 'the model answer is fine, as long as the grammar holds.',
      check: 'Check', next: 'Continue', understood: 'Got it', again: 'Practise again',
      good: 'pona!', notYet: 'Not quite', almost: 'Almost',
      yourSentence: 'your sentence', modelSentence: 'how it is built',
      variantRight: 'Correct — different words, same meaning',
      lookupOpen: 'look words up', lookupClose: 'close the lookup',
      lookupSearch: 'search a meaning or a word',
      lookupNone: 'Nothing found.',
      lookupTake: 'tap to drop the word in',
      particleMissing: (word, help) => `${word} is missing — ${help}`,
      particleExtra: (word, help) => `${word} is one too many — ${help}`,
      orderRight: 'Correct — modifiers may swap places',
      orderNote: 'Modifiers apply one after another. The order below is the usual one — '
        + 'it keeps set phrases together.',
      orderWrong: 'All the right words — but in this order they say something else.',
      model: 'Model answer:', comesBack: 'This will come back in one of the next reviews.',
      structureOk: '✓ structure is sound', structureLive: '✓ structure is sound',
      missing: (words) => `The structure holds, but this is missing: ${words}`,
      covers: (word, list) => `<b>${word}</b> covers: ${list}.`,
      literally: (tp, literal) => `<b>${tp}</b> — literally: ${literal}.`,
      glyphIs: (word, list) => `is <b>${word}</b> — ${list}.`,
      reviewDone: 'Review done',
      reviewNote: 'The cards return when it is time for them.',
      cards: 'cards', words: 'words', correct: 'correct', xp: 'xp',
      search: 'Search word or meaning …',
      sandboxTitle: 'o toki!',
      sandboxIntro: 'Write anything in toki pona. The parser takes it apart and tells you '
        + 'what it sees — or what does not hold.',
      sandboxQuestion: ' — a question', sandboxTry: 'Try:',
      sitelenHint: 'The writing system: one glyph per word. Switched on, every lesson gains '
        + 'a glyph exercise and the glyphs join the review queue. The course itself stays '
        + 'the same.',
      sitelenOn: 'Learn the glyphs', sitelenOff: 'Turn glyphs off',
      backupTitle: 'back up progress',
      backupState: (summary) => `Your progress lives on this device only: ${summary}. `
        + 'Safari clears it after seven days without a visit — not as a home screen app.',
      backupSave: 'Back up', backupLoad: 'Restore',
      backupFile: 'Save or share as a file', backupCopy: 'Copy code to clipboard',
      backupCopied: 'Copied. Keep it somewhere it will not get lost.',
      backupCopyFailed: 'Copying failed — use the file instead.',
      backupPick: 'Choose backup file', backupPaste: '… or paste the code here',
      backupUnreadable: 'That is not readable backup text.',
      backupForeign: 'There is no progress from this app in there.',
      backupUnreadableFile: 'The file could not be read.',
      backupFound: (found, exported, now) => `Found: ${found}`
        + `${exported ? ` · backed up on ${exported}` : ''}.<br>Replaces your current progress: ${now}.`,
      backupApply: 'Use this progress',
      summary: (lvl, lessons, cards, xp) => `level ${lvl}, ${lessons} lessons, ${cards} cards, ${xp} XP`,
      langLabel: 'language', langOther: 'Deutsch',
      askTrace: 'draw the glyph',
      traceClear: 'again',
      traceHint: 'Trace the template with your finger. Several strokes are fine.',
      traceThin: 'Part of the template is still missing.',
      traceWide: 'Too much beside it — stay on the line.',
      traceScore: (hit, clean) => `${hit}% of the template covered, ${clean}% of your line sits on it.`,
      cancel: 'cancel',
      tileHelp: (word) => `${word} — tap to remove, drag or use the arrow keys to reorder`,
      sentenceLabel: 'sentence',
      pageTitle: 'o toki! — learn toki pona',
      askCoin: 'say it without a word for it',
      coinHint: 'There is no word for this. Build one from the words there are — '
        + 'two or three will do.',
      coinGood: 'Works — you can say it like that',
      coinExact: 'Exactly the common version',
      coinUsual: (tp, lit) => `A common version is <code>${tp}</code> — literally ${lit}.`,
      coinThin: 'One word alone does not describe anything yet.',
      unknownWords: (list) => `Not a toki pona word: ${list}`,
      coinBroken: 'That does not add up as a phrase yet.',
      askStyle: 'which sentence says that?',
      styleTitle: 'nasin ante — more than one way',
      styleHint: 'Both sentences are correct. The difference is in what you mean.',
      askSyllable: 'build the word from syllables',
      syllableBack: (part) => `syllable ${part} — tap to take it back`,
      syllableHint: 'Every syllable has the shape (C)V(n) — there are no others.',
      syllableWord: (word, sense) => `${word} — ${sense}`,
      voiceTitle: 'kalama — spoken words',
      voiceHint: 'All 137 words are recorded twice, by kala Asi and by jan Lakuse '
        + '(Linku project). The app uses a real recording wherever there is one and '
        + 'falls back to the device voice for whole sentences.',
      voiceNames: { kalaasi: 'kala Asi', jlakuse: 'jan Lakuse', ante: 'alternating',
                    ilo: 'device voice' },
      voiceFetch: 'keep them offline', voiceFetching: (n, all) => `fetching … ${n}/${all}`,
      voiceReady: 'stored on the device', voiceFailed: 'Fetching failed.',
      voiceCredit: 'Recordings: kala Asi (CC BY-SA 4.0) and jan Lakuse · Linku project',
      recTitle: 'your own recordings',
      recHint: 'The app speaks with your device voice. Record a word yourself and '
        + 'it will use yours — everywhere the ♪ appears.',
      recStart: 'record', recStop: 'done', recBusy: '● recording',
      recCount: (n) => `${n} recording(s) of your own`,
      recDrop: 'delete all',
      recDenied: 'No access to the microphone.',
      recNone: 'This device cannot record.',
      recSaved: (word) => `“${word}” recorded`,
      cardMake: 'sentence card', cardShare: 'share', cardSave: 'save',
      cardFailed: 'The picture could not be built.',
      mapTitle: 'nimi ale — the whole language',
      mapHint: 'One box per word. It takes colour once you have met it and turns '
        + 'gold once it sticks.',
      mapCount: (known, all) => `${known} of ${all} met`,
      mapFirm: (n) => `${n} are solid`,
      mapLegend: ['unknown', 'met', 'practised', 'solid'],
      netOpen: (word) => `show word partnerships for ${word}`,
      netAsHead: 'as head word', netAsMod: 'as modifier',
      netNone: 'No combinations for this one in the corpus yet.',
      netHint: 'Word partnerships from every sentence in the app — this is how '
        + 'toki pona is actually put together.',
      nameTitle: 'nimi sina — your name in toki pona',
      nameHint: 'toki pona has fourteen letters and only syllables of the '
        + 'shape (C)V(n). Foreign names are therefore not translated but '
        + 'echoed — and always follow a head word.',
      namePlaceholder: 'name or foreign word',
      nameHeads: { jan: 'person', ma: 'place', toki: 'language', ilo: 'thing' },
      nameEmpty: 'Write something in there.',
      phraseTitle: 'toki lon — everyday sentences',
      phraseHint: 'What people actually say. Tap a word to look it up.',
      phrasePractice: 'practise everyday sentences',
      phraseLiteral: 'literally',
      skip: 'skip',
      skipNote: 'Skipped — it will come back shortly.',
      readTitle: 'lipu — reading',
      readHint: 'Texts that hang together. Tap a line and the translation appears; '
        + 'guessing first pays off.',
      readReveal: 'translation',
      readAll: 'read the whole text', readStop: 'quiet',
      readShowAll: 'all translations', readHideAll: 'cover again',
      readCount: (done, all) => `${done} of ${all} read`,
      readLocked: (stage) => `from lesson ${stage}`,
      readQuestions: 'Questions about the text',
      readBack: 'back',
      askQuiz: 'about the text',
      askJoin: 'make one sentence out of these',
      joinParts: 'from:',
      joinLa: '<b>la</b> puts the frame up front: frame first, then <b>la</b>, then the sentence.',
      joinPi: '<b>pi</b> regroups: everything after <b>pi</b> belongs to the head word before it.',
      weekTitle: 'this week',
      weekDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      weekSum: (xp, days) => `${xp} XP in seven days · ${days} day(s) on target`,
      goalTitle: 'daily goal',
      goalHint: 'How much do you want to take on in a day? One exercise is worth ten points.',
      goalPick: (xp) => `${xp} XP`,
      askAnswer: 'answer freely',
      answerHint: 'Your answer, your sentence. What gets checked is the build.',
      answerNeeds: (what) => `The answer needs ${what}.`,
      answerMissing: (what) => `Still missing: ${what}.`,
      answerEcho: 'That is the question itself — answer it.',
      answerFree: 'Well built — and your own answer',
      answerAlso: 'Others would have said:',
      answerEmpty: 'One word is not enough yet.',
      listen: 'listen', listenAgain: 'play again',
      askListen: 'what do you hear?',
      askDictation: 'write what you hear',
      dictationHint: 'Listen first, then type. The button plays it again.',
      dictationRight: 'Word for word',
      soundTitle: 'pronunciation',
      soundHint: 'toki pona is spoken the way it is written: five vowels, no lengthening, '
        + 'stress always on the first syllable. Single words come from kala Asi (Linku '
        + 'project, CC BY-SA), whole sentences from your device voice. Switched on, every '
        + 'lesson gains a listening task.',
      soundOn: 'Turn pronunciation on', soundOff: 'Turn pronunciation off',
      soundNone: 'This device has no speech output.',
      soundFailed: 'No sound comes out here.',
      soundSwitch: 'If tapping stays silent, the device is usually the reason: '
        + 'iPhones mute the recordings along with everything else via the ring switch. '
        + 'Under kalama there is „device voice“ — it speaks instead of the files.',
      musiTitle: 'utala musi',
      musiLead: 'Taunt, counter, make peace — with 137 words and not a single '
        + 'swear word.',
      musiStart: 'start the sparring',
      musiForgeTitle: 'nimi sin — freshly built',
      musiForgeHint: 'One pattern, many fillings. The parser checks every roll '
        + 'before it lands here.',
      musiForge: 'One more', musiPattern: 'pattern',
      musiSting: 'cheek', musiLiteral: 'literally',
      musiSection: (name, count) => `${name} · ${count}`,
      musiPeace: 'And afterwards: <i>mi musi taso</i> — it was only play.',
      sizeTitle: 'length of a round',
      sizeHint: 'How many exercises a lesson holds. Short fits a train ride, '
        + 'long fits an evening. Reviews follow suit.',
      sizeShort: 'Short · 6', sizeMedium: 'Medium · 12', sizeLong: 'Long · 20',
      weakTitle: 'practise weak spots',
      weakSub: (n) => `${n} ${n === 1 ? 'thing has' : 'things have'} not settled yet`,
      weakDone: 'Weak spots done',
      weakNote: 'Whatever wobbles again will be waiting next time.',
      diaryTitle: 'o sitelen — diary',
      diaryHint: 'One sentence a day, written by you. The parser reads along '
        + 'but does not grade — it is your diary.',
      diaryOpen: 'Write today', diaryBack: 'Back',
      diaryLead: 'Write down how your day went. Short is fine.',
      diaryPrompt: 'A nudge for today',
      diaryPlaceholder: 'tenpo suno ni la mi …',
      diarySave: 'Save entry', diarySaved: 'Saved.',
      diaryEmpty: 'No entry yet. The first one is the hardest.',
      diaryCount: (n, days) => `${n} ${n === 1 ? 'entry' : 'entries'}`
        + `${days > 1 ? ` · ${days} days in a row` : ''}`,
      diaryToday: 'today', diaryXray: 'Show the structure',
      diaryReward: 'First entry today · +15 XP',
      diaryLines: (ok, all) => `${ok}/${all} sentences hold up`,
      updateReady: 'A new version is here.', updateLoad: 'Load it now',
      versionLabel: (v) => `Version ${v}`,
      credit: (link) => `Prototype. Exercise sentences from ${link} (MIT, © 2020 /dev/urandom `
        + 'and contributors), checked by TokiPonaKit.',
    },
  };
