// Lesen am Stück: kurze zusammenhängende Texte statt lauter Einzelsätze.
//
// Jede Zeile ist ein gültiger Satz (geprüft in prototype/test.js), die
// Übersetzung liegt darunter und wird erst auf Tippen sichtbar — erst raten,
// dann nachsehen. Danach ein paar Fragen zum Text.
const TOKIPONA_LIPU = {
  texts: [
    {
      id: 'lipu1', stage: 3,
      title: { de: 'soweli lili', en: 'soweli lili' },
      about: { de: 'Ein kleines Tier und sein Hunger.', en: 'A small animal and its hunger.' },
      lines: [
        { tp: 'soweli lili li lon ma.', de: 'Ein kleines Tier ist auf dem Land.',
          en: 'A small animal is in the land.' },
        { tp: 'ona li wile moku.', de: 'Es will essen.', en: 'It wants to eat.' },
        { tp: 'soweli li lukin e kili.', de: 'Das Tier sieht eine Frucht.',
          en: 'The animal sees a fruit.' },
        { tp: 'kili li suli.', de: 'Die Frucht ist groß.', en: 'The fruit is big.' },
        { tp: 'soweli li moku e kili.', de: 'Das Tier isst die Frucht.',
          en: 'The animal eats the fruit.' },
        { tp: 'soweli li pona.', de: 'Dem Tier geht es gut.', en: 'The animal is well.' },
      ],
      questions: [
        { tp: 'soweli li moku e seme?', de: 'Was isst das Tier?', en: 'What does the animal eat?',
          options: { de: ['die Frucht', 'das Land', 'Wasser'],
                     en: ['the fruit', 'the land', 'water'] }, right: 0 },
        { tp: 'kili li suli anu lili?', de: 'Ist die Frucht groß oder klein?',
          en: 'Is the fruit big or small?',
          options: { de: ['groß', 'klein', 'das steht nicht da'],
                     en: ['big', 'small', 'it does not say'] }, right: 0 },
      ],
    },
    {
      id: 'lipu2', stage: 6,
      title: { de: 'tomo mi', en: 'tomo mi' },
      about: { de: 'Ein Tag zwischen Haus und Stadt.', en: 'A day between house and town.' },
      lines: [
        { tp: 'mi lon tomo mi.', de: 'Ich bin in meinem Haus.', en: 'I am in my house.' },
        { tp: 'tomo mi li lili taso li pona.', de: 'Mein Haus ist klein, aber gut.',
          en: 'My house is small but good.' },
        { tp: 'tenpo suno la mi tawa ma tomo.', de: 'Am Tag gehe ich in die Stadt.',
          en: 'During the day I go to town.' },
        { tp: 'mi kepeken e tomo tawa.', de: 'Ich benutze ein Auto.', en: 'I use a car.' },
        { tp: 'jan pona mi li lon ma tomo.', de: 'Mein Freund ist in der Stadt.',
          en: 'My friend is in town.' },
        { tp: 'mi moku lon tomo pi jan pona mi.', de: 'Ich esse im Haus meines Freundes.',
          en: 'I eat at my friend’s house.' },
        { tp: 'tenpo pimeja la mi tawa tomo mi.', de: 'In der Nacht gehe ich nach Hause.',
          en: 'At night I go back to my house.' },
      ],
      questions: [
        { tp: 'mi tawa seme lon tenpo suno?', de: 'Wohin geht die Erzählerin am Tag?',
          en: 'Where does the narrator go during the day?',
          options: { de: ['in die Stadt', 'ins Bett', 'aufs Land'],
                     en: ['to town', 'to bed', 'to the countryside'] }, right: 0 },
        { tp: 'mi moku lon seme?', de: 'Wo wird gegessen?', en: 'Where is the eating done?',
          options: { de: ['im Haus des Freundes', 'im eigenen Haus', 'im Auto'],
                     en: ['at the friend’s house', 'at home', 'in the car'] }, right: 0 },
      ],
    },
    {
      id: 'lipu3', stage: 9,
      title: { de: 'jan pi toki pona', en: 'jan pi toki pona' },
      about: { de: 'Warum jemand diese Sprache lernt.', en: 'Why someone learns this language.' },
      lines: [
        { tp: 'jan Ana li jan pi toki pona.', de: 'Ana ist ein toki-pona-Mensch.',
          en: 'Ana is a toki pona person.' },
        { tp: 'tenpo pini la ona li sona ala e nimi.', de: 'Früher kannte sie die Wörter nicht.',
          en: 'Earlier she did not know the words.' },
        { tp: 'ona li kama sona e nimi mute.', de: 'Sie lernte viele Wörter.',
          en: 'She learned many words.' },
        { tp: 'nimi li lili taso toki li suli.', de: 'Die Wörter sind wenige, aber die Sprache ist groß.',
          en: 'The words are few but the language is large.' },
        { tp: 'tenpo ni la ona li toki e ijo ale.', de: 'Jetzt sagt sie alles.',
          en: 'Now she says everything.' },
        { tp: 'toki pona li pona tawa ona.', de: 'toki pona gefällt ihr.',
          en: 'She likes toki pona.' },
      ],
      questions: [
        { tp: 'jan Ana li kama sona e seme?', de: 'Was hat Ana gelernt?', en: 'What did Ana learn?',
          options: { de: ['viele Wörter', 'ein Lied', 'gar nichts'],
                     en: ['many words', 'a song', 'nothing at all'] }, right: 0 },
        { tp: 'nimi li mute anu lili?', de: 'Sind es viele Wörter oder wenige?',
          en: 'Are the words many or few?',
          options: { de: ['wenige', 'viele', 'das steht nicht da'],
                     en: ['few', 'many', 'it does not say'] }, right: 0 },
      ],
    },
    {
      id: 'lipu4', stage: 11,
      title: { de: 'tenpo mute', en: 'tenpo mute' },
      about: { de: 'Zählen, warten, weitermachen.', en: 'Counting, waiting, carrying on.' },
      lines: [
        { tp: 'mi jo e soweli tu.', de: 'Ich habe zwei Tiere.', en: 'I have two animals.' },
        { tp: 'soweli wan li suli. soweli wan li lili.',
          de: 'Ein Tier ist groß. Ein Tier ist klein.',
          en: 'One animal is big. One animal is small.' },
        { tp: 'tenpo suno luka la mi pana e moku tawa ona.',
          de: 'Fünf Tage lang gebe ich ihnen Essen.',
          en: 'For five days I give them food.' },
        { tp: 'ona li kama suli.', de: 'Sie werden groß.', en: 'They grow big.' },
        { tp: 'tenpo kama la mi jo e soweli mute.',
          de: 'Später habe ich viele Tiere.', en: 'Later I will have many animals.' },
      ],
      questions: [
        { tp: 'mi jo e soweli mute seme?', de: 'Wie viele Tiere sind es am Anfang?',
          en: 'How many animals are there at the start?',
          options: { de: ['zwei', 'fünf', 'viele'], en: ['two', 'five', 'many'] }, right: 0 },
        { tp: 'mi pana e seme tawa soweli?', de: 'Was bekommen die Tiere?',
          en: 'What do the animals get?',
          options: { de: ['Essen', 'Wasser', 'ein Haus'], en: ['food', 'water', 'a house'] }, right: 0 },
      ],
    },
  ],
};

if (typeof module !== 'undefined') { module.exports = TOKIPONA_LIPU; }
