// Lesen am Stück: kurze zusammenhängende Texte statt lauter Einzelsätze.
//
// Zwei Regeln, die prototype/test.js durchsetzt:
//   1. Jede Zeile ist ein gültiger Satz.
//   2. Kein Text benutzt ein Wort, das seine Lektion noch nicht eingeführt
//      hat — sonst liest man Zeichen statt Sprache.
// Deshalb sind die frühen Texte karg: vor Lektion 7 gibt es kein Fragewort,
// die Fragen dazu stehen dann nur auf Deutsch beziehungsweise Englisch.
const TOKIPONA_LIPU = {
  texts: [
    {
      id: 'lipu1', stage: 2,
      title: { de: 'jan lili', en: 'jan lili' },
      about: { de: 'Ein Kind, eine Mama, ein Tier.', en: 'A child, a mother, an animal.' },
      lines: [
        { tp: 'mi jan lili.', de: 'Ich bin ein Kind.', en: 'I am a child.' },
        { tp: 'mama mi li suli.', de: 'Meine Mama ist groß.', en: 'My mother is big.' },
        { tp: 'mama mi li pona.', de: 'Meine Mama ist gut.', en: 'My mother is good.' },
        { tp: 'soweli mi li lili li suwi.', de: 'Mein Tier ist klein und süß.',
          en: 'My animal is small and sweet.' },
        { tp: 'soweli li moku.', de: 'Das Tier frisst.', en: 'The animal eats.' },
        { tp: 'mi moku.', de: 'Ich esse.', en: 'I eat.' },
        { tp: 'mi pona.', de: 'Mir geht es gut.', en: 'I am well.' },
      ],
      questions: [
        { de: 'Wie ist das Tier?', en: 'What is the animal like?',
          options: { de: ['klein und süß', 'groß und böse', 'krank'],
                     en: ['small and sweet', 'big and bad', 'sick'] }, right: 0 },
        { de: 'Wer ist groß?', en: 'Who is big?',
          options: { de: ['die Mama', 'das Kind', 'das Tier'],
                     en: ['the mother', 'the child', 'the animal'] }, right: 0 },
      ],
    },
    {
      id: 'lipu2', stage: 3,
      title: { de: 'tomo mi', en: 'tomo mi' },
      about: { de: 'Was in einem kleinen Haus passiert.', en: 'What happens in a small house.' },
      lines: [
        { tp: 'mi lukin e tomo mi.', de: 'Ich schaue mein Haus an.', en: 'I look at my house.' },
        { tp: 'tomo li suli ala. tomo li lili.', de: 'Das Haus ist nicht groß. Es ist klein.',
          en: 'The house is not big. It is small.' },
        { tp: 'mi pali e moku.', de: 'Ich mache Essen.', en: 'I make food.' },
        { tp: 'mama mi li moku e telo.', de: 'Meine Mama trinkt Wasser.',
          en: 'My mother drinks water.' },
        { tp: 'mi pana e lipu.', de: 'Ich reiche ein Buch herüber.', en: 'I hand over a book.' },
        { tp: 'mama mi li lukin e lipu.', de: 'Meine Mama liest das Buch.',
          en: 'My mother reads the book.' },
        { tp: 'mi olin e mama mi.', de: 'Ich liebe meine Mama.', en: 'I love my mother.' },
      ],
      questions: [
        { de: 'Was macht das Kind?', en: 'What does the child do?',
          options: { de: ['Essen', 'ein Buch', 'ein Haus'], en: ['food', 'a book', 'a house'] },
          right: 0 },
        { de: 'Was bekommt die Mama?', en: 'What does the mother get?',
          options: { de: ['ein Buch', 'Wasser', 'ein Tier'], en: ['a book', 'water', 'an animal'] },
          right: 0 },
      ],
    },
    {
      id: 'lipu3', stage: 4,
      title: { de: 'ma pona', en: 'ma pona' },
      about: { de: 'Draußen: Pflanzen, Vögel, Käfer.', en: 'Outside: plants, birds, bugs.' },
      lines: [
        { tp: 'ma li suli li pona.', de: 'Das Land ist groß und schön.',
          en: 'The land is large and good.' },
        { tp: 'kasi li lili. kasi li suwi.', de: 'Die Pflanze ist klein. Sie ist süß.',
          en: 'The plant is small. It is sweet.' },
        { tp: 'waso li moku e pipi.', de: 'Der Vogel frisst einen Käfer.',
          en: 'The bird eats a bug.' },
        { tp: 'telo li suli. kala li moku.', de: 'Das Wasser ist groß. Die Fische fressen.',
          en: 'The water is large. The fish eat.' },
        { tp: 'mi jo e sitelen.', de: 'Ich habe ein Bild.', en: 'I have a picture.' },
        { tp: 'mi pali e sitelen ma.', de: 'Ich male ein Bild vom Land.',
          en: 'I make a picture of the land.' },
        { tp: 'mi toki e toki pona.', de: 'Ich spreche toki pona.', en: 'I speak toki pona.' },
      ],
      questions: [
        { de: 'Was frisst der Vogel?', en: 'What does the bird eat?',
          options: { de: ['einen Käfer', 'einen Fisch', 'eine Pflanze'],
                     en: ['a bug', 'a fish', 'a plant'] }, right: 0 },
        { de: 'Was macht die Erzählerin?', en: 'What does the narrator make?',
          options: { de: ['ein Bild', 'ein Haus', 'Essen'], en: ['a picture', 'a house', 'food'] },
          right: 0 },
      ],
    },
    {
      id: 'lipu4', stage: 5,
      title: { de: 'kulupu mi', en: 'kulupu mi' },
      about: { de: 'Eine Gruppe, ein Feuer, ein Lied.', en: 'A group, a fire, a song.' },
      lines: [
        { tp: 'mi en jan pona mi li kulupu.', de: 'Meine Freunde und ich sind eine Gruppe.',
          en: 'My friends and I are a group.' },
        { tp: 'kulupu li mute.', de: 'Die Gruppe ist groß (viele).', en: 'The group is many.' },
        { tp: 'seli li suli.', de: 'Das Feuer ist groß.', en: 'The fire is big.' },
        { tp: 'jan ante li kalama.', de: 'Ein anderer Mensch macht Musik.',
          en: 'Another person makes sound.' },
        { tp: 'kalama ni li pona.', de: 'Dieser Klang ist schön.', en: 'This sound is good.' },
        { tp: 'jan mute li lape ala. mi lape.', de: 'Viele schlafen nicht. Ich schlafe.',
          en: 'Many do not sleep. I sleep.' },
        { tp: 'ni li pona.', de: 'Das ist gut so.', en: 'That is good.' },
      ],
      questions: [
        { de: 'Wer schläft?', en: 'Who sleeps?',
          options: { de: ['die Erzählerin', 'die ganze Gruppe', 'niemand'],
                     en: ['the narrator', 'the whole group', 'nobody'] }, right: 0 },
        { de: 'Was macht der andere Mensch?', en: 'What does the other person do?',
          options: { de: ['Musik', 'Feuer', 'Essen'], en: ['sound', 'fire', 'food'] }, right: 0 },
      ],
    },
    {
      id: 'lipu5', stage: 6,
      title: { de: 'nasin mi', en: 'nasin mi' },
      about: { de: 'Ein Weg hinaus und wieder zurück.', en: 'A way out and back again.' },
      lines: [
        { tp: 'mi lon tomo mi.', de: 'Ich bin in meinem Haus.', en: 'I am in my house.' },
        { tp: 'mi tawa ma.', de: 'Ich gehe hinaus aufs Land.', en: 'I go out to the land.' },
        { tp: 'mi tawa kepeken noka mi.', de: 'Ich gehe zu Fuß.', en: 'I travel using my legs.' },
        { tp: 'soweli li tawa poka mi.', de: 'Ein Tier läuft neben mir.',
          en: 'An animal walks beside me.' },
        { tp: 'mi lukin e waso lon sewi.', de: 'Ich sehe Vögel oben.',
          en: 'I see birds up above.' },
        { tp: 'mi awen lon ma.', de: 'Ich bleibe draußen.', en: 'I stay in the land.' },
        { tp: 'mi pona tan ni.', de: 'Davon geht es mir gut.', en: 'I am well from that.' },
        { tp: 'mi tawa tomo mi.', de: 'Ich gehe nach Hause.', en: 'I go to my house.' },
      ],
      questions: [
        { de: 'Womit ist die Erzählerin unterwegs?', en: 'How does the narrator travel?',
          options: { de: ['zu Fuß', 'mit dem Auto', 'mit dem Tier'],
                     en: ['on foot', 'by car', 'on the animal'] }, right: 0 },
        { de: 'Wo sind die Vögel?', en: 'Where are the birds?',
          options: { de: ['oben', 'neben ihr', 'im Haus'],
                     en: ['above', 'beside her', 'in the house'] }, right: 0 },
      ],
    },
    {
      id: 'lipu6', stage: 7,
      title: { de: 'toki tu', en: 'toki tu' },
      about: { de: 'Zwei Menschen reden. Ein Gespräch zum Mitlesen.',
               en: 'Two people talking. A dialogue to read along.' },
      lines: [
        { tp: 'jan Ana o!', de: 'Ana!', en: 'Ana!' },
        { tp: 'sina pona anu ike?', de: 'Geht es dir gut oder schlecht?',
          en: 'Are you well or unwell?' },
        { tp: 'mi pona a!', de: 'Mir geht es gut!', en: 'I am well!' },
        { tp: 'sina pali e seme?', de: 'Was machst du?', en: 'What are you making?' },
        { tp: 'mi pali e ilo.', de: 'Ich baue ein Werkzeug.', en: 'I am making a tool.' },
        { tp: 'ilo li seme?', de: 'Was für ein Werkzeug?', en: 'What kind of tool?' },
        { tp: 'o kute! ilo li kalama.', de: 'Hör mal! Das Werkzeug macht Geräusche.',
          en: 'Listen! The tool makes sound.' },
        { tp: 'mu a! ilo sina li pona.', de: 'Oha! Dein Werkzeug ist gut.',
          en: 'Wow! Your tool is good.' },
      ],
      questions: [
        { tp: 'jan li pali e seme?', de: 'Was baut der Mensch?', en: 'What is the person making?',
          options: { de: ['ein Werkzeug', 'ein Haus', 'Essen'],
                     en: ['a tool', 'a house', 'food'] }, right: 0 },
        { tp: 'ilo li pali e seme?', de: 'Was macht das Werkzeug?', en: 'What does the tool do?',
          options: { de: ['Geräusche', 'Essen', 'gar nichts'],
                     en: ['sound', 'food', 'nothing at all'] }, right: 0 },
      ],
    },
    {
      id: 'lipu7', stage: 8,
      title: { de: 'kule ale', en: 'kule ale' },
      about: { de: 'Ein Bild entsteht, Farbe für Farbe.', en: 'A picture appears, colour by colour.' },
      lines: [
        { tp: 'mi pali e sitelen.', de: 'Ich male ein Bild.', en: 'I make a picture.' },
        { tp: 'kasi li laso.', de: 'Die Pflanzen sind grün.', en: 'The plants are green.' },
        { tp: 'kili li loje li suwi.', de: 'Die Frucht ist rot und süß.',
          en: 'The fruit is red and sweet.' },
        { tp: 'waso li walo li lili.', de: 'Der Vogel ist weiß und klein.',
          en: 'The bird is white and small.' },
        { tp: 'ma li pimeja. mi lukin ala.', de: 'Das Land ist dunkel. Ich sehe nichts.',
          en: 'The land is dark. I do not see.' },
        { tp: 'soweli nasa li moku e jaki.', de: 'Ein komisches Tier frisst Dreck.',
          en: 'A strange animal eats filth.' },
        { tp: 'mi lukin e kule mute. mi pona.', de: 'Ich sehe viele Farben. Mir geht es gut.',
          en: 'I see many colours. I am well.' },
      ],
      questions: [
        { tp: 'kili li kule seme?', de: 'Welche Farbe hat die Frucht?',
          en: 'What colour is the fruit?',
          options: { de: ['rot', 'grün', 'weiß'], en: ['red', 'green', 'white'] }, right: 0 },
        { tp: 'soweli li moku e seme?', de: 'Was frisst das komische Tier?',
          en: 'What does the strange animal eat?',
          options: { de: ['Dreck', 'die Frucht', 'den Vogel'],
                     en: ['filth', 'the fruit', 'the bird'] }, right: 0 },
      ],
    },
    {
      id: 'lipu8', stage: 9,
      title: { de: 'jan pi toki pona', en: 'jan pi toki pona' },
      about: { de: 'Warum jemand bei dieser Sprache bleibt.',
               en: 'Why someone sticks with this language.' },
      lines: [
        { tp: 'jan Ana li jan pi toki pona.', de: 'Ana ist ein toki-pona-Mensch.',
          en: 'Ana is a toki pona person.' },
        { tp: 'nimi li lili. toki li suli.',
          de: 'Die Wörter sind wenige. Die Sprache ist groß.',
          en: 'The words are few. The language is large.' },
        { tp: 'ona li sitelen e linja lon lipu.', de: 'Sie zeichnet Striche auf Papier.',
          en: 'She draws lines on paper.' },
        { tp: 'luka ona li lete.', de: 'Ihre Hände sind kalt.', en: 'Her hands are cold.' },
        { tp: 'ni la ona li musi.', de: 'Trotzdem hat sie Spaß.', en: 'Even so she has fun.' },
        { tp: 'jan pi toki pona li kulupu pona.', de: 'Die toki-pona-Leute sind eine gute Gruppe.',
          en: 'The toki pona people are a good group.' },
        { tp: 'mi toki lon kulupu ni.', de: 'Ich rede in dieser Gruppe.',
          en: 'I speak in this group.' },
      ],
      questions: [
        { tp: 'jan Ana li sitelen e seme?', de: 'Was zeichnet Ana?', en: 'What does Ana draw?',
          options: { de: ['Striche', 'ein Tier', 'ein Haus'],
                     en: ['lines', 'an animal', 'a house'] }, right: 0 },
        { tp: 'nimi li mute anu lili?', de: 'Sind es viele Wörter oder wenige?',
          en: 'Are the words many or few?',
          options: { de: ['wenige', 'viele', 'das steht nicht da'],
                     en: ['few', 'many', 'it does not say'] }, right: 0 },
      ],
    },
    {
      id: 'lipu9', stage: 10,
      title: { de: 'kama sona', en: 'kama sona' },
      about: { de: 'Wie das Lernen anfing und weiterging.',
               en: 'How the learning started and kept going.' },
      lines: [
        { tp: 'tenpo pini la mi sona ala e toki pona.',
          de: 'Früher konnte ich kein toki pona.', en: 'Earlier I did not know toki pona.' },
        { tp: 'mi lukin e lipu. mi sona ala e nimi.',
          de: 'Ich sah ein Buch an. Ich kannte die Wörter nicht.',
          en: 'I looked at a book. I did not know the words.' },
        { tp: 'mi wile kama sona.', de: 'Ich wollte lernen.', en: 'I wanted to learn.' },
        { tp: 'mi open e nasin.', de: 'Ich schlug einen Weg ein.', en: 'I started on a path.' },
        { tp: 'tenpo mute la mi pali.', de: 'Lange Zeit habe ich geübt.',
          en: 'For a long time I worked at it.' },
        { tp: 'tenpo ni la mi ken toki.', de: 'Jetzt kann ich sprechen.', en: 'Now I can speak.' },
        { tp: 'mi pini ala. mi awen kama sona.',
          de: 'Ich höre nicht auf. Ich lerne weiter.',
          en: 'I am not finished. I keep learning.' },
      ],
      questions: [
        { tp: 'tenpo pini la mi sona ala e seme?', de: 'Was konnte die Erzählerin früher nicht?',
          en: 'What did the narrator not know earlier?',
          options: { de: ['toki pona', 'lesen', 'schlafen'],
                     en: ['toki pona', 'reading', 'sleeping'] }, right: 0 },
        { tp: 'tenpo ni la mi ken seme?', de: 'Was kann sie jetzt?', en: 'What can she do now?',
          options: { de: ['sprechen', 'gar nichts', 'schlafen'],
                     en: ['speak', 'nothing at all', 'sleep'] }, right: 0 },
      ],
    },
    {
      id: 'lipu10', stage: 11,
      title: { de: 'tenpo mute', en: 'tenpo mute' },
      about: { de: 'Zählen, warten, weitermachen.', en: 'Counting, waiting, carrying on.' },
      lines: [
        { tp: 'mi jo e soweli tu.', de: 'Ich habe zwei Tiere.', en: 'I have two animals.' },
        { tp: 'soweli wan li suli. soweli ante li lili.',
          de: 'Ein Tier ist groß. Das andere ist klein.',
          en: 'One animal is big. The other is small.' },
        { tp: 'tenpo suno luka la mi pana e moku tawa ona.',
          de: 'Fünf Tage lang gebe ich ihnen Essen.', en: 'For five days I give them food.' },
        { tp: 'ona li kama suli.', de: 'Sie werden groß.', en: 'They grow big.' },
        { tp: 'mi esun e moku kepeken mani mi.',
          de: 'Ich kaufe das Essen mit meinem Geld.', en: 'I buy the food with my money.' },
        { tp: 'tenpo pimeja la mun li lon sewi.',
          de: 'Nachts steht der Mond oben.', en: 'At night the moon is up above.' },
        { tp: 'tenpo kama la mi jo e soweli mute.',
          de: 'Später habe ich viele Tiere.', en: 'Later I will have many animals.' },
      ],
      questions: [
        { tp: 'mi jo e soweli mute seme?', de: 'Wie viele Tiere sind es am Anfang?',
          en: 'How many animals are there at the start?',
          options: { de: ['zwei', 'fünf', 'viele'], en: ['two', 'five', 'many'] }, right: 0 },
        { tp: 'mi esun kepeken seme?', de: 'Womit wird gekauft?', en: 'What is used to buy?',
          options: { de: ['mit Geld', 'mit Essen', 'mit einem Tier'],
                     en: ['with money', 'with food', 'with an animal'] }, right: 0 },
      ],
    },
  ],
};

if (typeof module !== 'undefined') { module.exports = TOKIPONA_LIPU; }
