// Spaßmodus „utala musi“ — Sticheleien, Konter und Friedensschlüsse.
//
// toki pona hat keine Schimpfwörter: 137 Wörter, keines davon derb. Wer
// jemanden aufziehen will, muss umschreiben — und genau das übt hier die
// Grammatik. Jede Zeile ist ein vollständiger Satz und läuft durch denselben
// Parser wie der Kurs (siehe prototype/test.js).
const TOKIPONA_MUSI = {
  intro: {
    de: 'toki pona kennt keine Schimpfwörter. Mit 137 Wörtern muss man '
      + 'umschreiben — und darin liegt der Witz: <i>lawa sina li lili</i> ist '
      + 'kein Fluch, sondern ein Bild. Unter Sprechenden gehört dazu, hinterher '
      + '<i>mi musi taso</i> zu sagen — es war nur Spaß.',
    en: 'toki pona has no swear words. With 137 words you have to talk around '
      + 'things — and that is where the fun is: <i>lawa sina li lili</i> is not '
      + 'a curse, it is a picture. Among speakers it belongs to the game to add '
      + '<i>mi musi taso</i> afterwards — it was only play.',
  },

  kinds: {
    utala: { de: 'Stichelei', en: 'taunt' },
    konter: { de: 'Konter', en: 'comeback' },
    wawa: { de: 'Angeberei', en: 'boast' },
    pona: { de: 'Frieden', en: 'peace' },
  },

  // sting: 1 = harmlos, 2 = frech, 3 = ordentlich frech (mehr geht nicht).
  lines: [
    { id: 'musi-01', kind: 'utala', sting: 1, tp: 'sina jaki.',
      de: ['Du bist eklig.'], en: ['You are gross.'],
      lit: { de: 'du · eklig', en: 'you · gross' } },
    { id: 'musi-02', kind: 'utala', sting: 2, tp: 'lawa sina li lili.',
      de: ['Dein Kopf ist klein.'], en: ['Your head is small.'],
      lit: { de: 'Kopf · dein · ist · klein', en: 'head · your · is · small' } },
    { id: 'musi-03', kind: 'utala', sting: 2, tp: 'sina sona ala e toki pona.',
      de: ['Du kannst kein toki pona.'], en: ['You do not know toki pona.'],
      lit: { de: 'du · kennst · nicht · [Objekt] · toki pona',
             en: 'you · know · not · [object] · toki pona' } },
    { id: 'musi-04', kind: 'utala', sting: 1, tp: 'toki sina li nasa.',
      de: ['Dein Gerede ist wirr.'], en: ['Your talk is strange.'],
      lit: { de: 'Rede · deine · ist · wirr', en: 'talk · your · is · strange' } },
    { id: 'musi-05', kind: 'utala', sting: 2, tp: 'sina soweli lili.',
      de: ['Du bist ein kleines Tier.'], en: ['You are a small animal.'],
      lit: { de: 'du · Tier · klein', en: 'you · animal · small' } },
    { id: 'musi-06', kind: 'utala', sting: 2, tp: 'sina moku e jaki.',
      de: ['Du isst Müll.'], en: ['You eat garbage.'],
      lit: { de: 'du · isst · [Objekt] · Dreck', en: 'you · eat · [object] · filth' } },
    { id: 'musi-07', kind: 'utala', sting: 1, tp: 'sina lape taso.',
      de: ['Du schläfst nur.'], en: ['You only sleep.'],
      lit: { de: 'du · schläfst · nur', en: 'you · sleep · only' } },
    { id: 'musi-08', kind: 'utala', sting: 2, tp: 'nimi sina li suli ala.',
      de: ['Dein Wort wiegt nichts.'], en: ['Your word carries no weight.'],
      lit: { de: 'Name · dein · ist · groß · nicht', en: 'name · your · is · big · not' } },
    { id: 'musi-09', kind: 'utala', sting: 1, tp: 'sina pu ala.',
      de: ['Du hast das Buch nicht gelesen.'], en: ['You have not read the book.'],
      lit: { de: 'du · [mit dem Buch umgehen] · nicht',
             en: 'you · [engage with the book] · not' } },
    { id: 'musi-10', kind: 'utala', sting: 2, tp: 'sina ken ala toki.',
      de: ['Reden kannst du nicht.'], en: ['You cannot talk.'],
      lit: { de: 'du · kannst · nicht · reden', en: 'you · can · not · talk' } },
    { id: 'musi-11', kind: 'utala', sting: 3, tp: 'monsi sina li suli.',
      de: ['Dein Hintern ist groß.'], en: ['Your behind is big.'],
      lit: { de: 'Rückseite · deine · ist · groß', en: 'behind · your · is · big' } },
    { id: 'musi-12', kind: 'utala', sting: 3, tp: 'sina pana e kon jaki.',
      de: ['Du verteilst schlechte Luft.'], en: ['You give off bad air.'],
      lit: { de: 'du · gibst · [Objekt] · Luft · eklig',
             en: 'you · give · [object] · air · foul' } },
    { id: 'musi-13', kind: 'utala', sting: 2, tp: 'sina jan pi sona ala.',
      de: ['Du bist ein Mensch ohne Ahnung.'], en: ['You are a person without knowledge.'],
      lit: { de: 'du · Mensch · von · Wissen · nicht',
             en: 'you · person · of · knowing · not' } },
    { id: 'musi-14', kind: 'utala', sting: 3, tp: 'soweli sina taso li olin e sina.',
      de: ['Nur dein Haustier hat dich lieb.'], en: ['Only your pet loves you.'],
      lit: { de: 'Tier · dein · nur · liebt · [Objekt] · dich',
             en: 'animal · your · only · loves · [object] · you' } },
    { id: 'musi-15', kind: 'utala', sting: 2, tp: 'sina wile e telo.',
      de: ['Du brauchst Wasser.'], en: ['You need water.'],
      lit: { de: 'du · brauchst · [Objekt] · Wasser', en: 'you · want · [object] · water' } },
    { id: 'musi-16', kind: 'utala', sting: 2, tp: 'uta sina li open lon tenpo ale.',
      de: ['Dein Mund ist immer offen.'], en: ['Your mouth is open all the time.'],
      lit: { de: 'Mund · dein · ist · offen · zu · Zeit · aller',
             en: 'mouth · your · is · open · at · time · all' } },
    { id: 'musi-17', kind: 'utala', sting: 2, tp: 'sina pali ala e ijo pona.',
      de: ['Du bringst nichts Gutes zustande.'], en: ['You make nothing good.'],
      lit: { de: 'du · machst · nicht · [Objekt] · Ding · gut',
             en: 'you · make · not · [object] · thing · good' } },
    { id: 'musi-18', kind: 'utala', sting: 1, tp: 'sina toki e ijo lili taso.',
      de: ['Du redest nur über Kleinkram.'], en: ['You only talk about little things.'],
      lit: { de: 'du · sprichst · [Objekt] · Ding · klein · nur',
             en: 'you · say · [object] · thing · small · only' } },

    { id: 'musi-19', kind: 'konter', sting: 1, tp: 'mi kute ala e sina.',
      de: ['Ich höre dir nicht zu.'], en: ['I am not listening to you.'],
      lit: { de: 'ich · höre · nicht · [Objekt] · dich',
             en: 'I · hear · not · [object] · you' } },
    { id: 'musi-20', kind: 'konter', sting: 2, tp: 'toki sina li pona ala tawa mi.',
      de: ['Dein Gerede gefällt mir nicht.'], en: ['Your talk is not good to me.'],
      lit: { de: 'Rede · deine · ist · gut · nicht · für · mich',
             en: 'talk · your · is · good · not · to · me' } },
    { id: 'musi-21', kind: 'konter', sting: 1, tp: 'mi sona e sina.',
      de: ['Ich kenne dich.'], en: ['I know you.'],
      lit: { de: 'ich · kenne · [Objekt] · dich', en: 'I · know · [object] · you' } },
    { id: 'musi-22', kind: 'konter', sting: 2, tp: 'o toki ala e ni.',
      de: ['Sag so etwas nicht.'], en: ['Do not say that.'],
      lit: { de: '[Befehl] · sag · nicht · [Objekt] · das',
             en: '[command] · say · not · [object] · this' } },
    { id: 'musi-23', kind: 'konter', sting: 1, tp: 'mi pona mute.',
      de: ['Mir geht es blendend.'], en: ['I am doing great.'],
      lit: { de: 'ich · gut · sehr', en: 'I · good · very' } },
    { id: 'musi-24', kind: 'konter', sting: 2, tp: 'nimi sina li kama ala tawa mi.',
      de: ['Deine Worte erreichen mich nicht.'], en: ['Your words do not reach me.'],
      lit: { de: 'Wort · dein · kommt · nicht · zu · mir',
             en: 'word · your · comes · not · to · me' } },

    { id: 'musi-25', kind: 'wawa', sting: 1, tp: 'mi wawa mute.',
      de: ['Ich bin sehr stark.'], en: ['I am very strong.'],
      lit: { de: 'ich · stark · sehr', en: 'I · strong · very' } },
    { id: 'musi-26', kind: 'wawa', sting: 1, tp: 'mi sona e toki pona.',
      de: ['Ich kann toki pona.'], en: ['I know toki pona.'],
      lit: { de: 'ich · kenne · [Objekt] · toki pona',
             en: 'I · know · [object] · toki pona' } },
    { id: 'musi-27', kind: 'wawa', sting: 1, tp: 'mi jan pi sona suli.',
      de: ['Ich bin ein Mensch mit großem Wissen.'], en: ['I am a person of great knowledge.'],
      lit: { de: 'ich · Mensch · von · Wissen · groß',
             en: 'I · person · of · knowledge · great' } },
    { id: 'musi-28', kind: 'wawa', sting: 2, tp: 'mi ken utala e sina.',
      de: ['Ich könnte dich besiegen.'], en: ['I could fight you.'],
      lit: { de: 'ich · kann · kämpfen · [Objekt] · dich',
             en: 'I · can · fight · [object] · you' } },
    { id: 'musi-29', kind: 'wawa', sting: 1, tp: 'mi awen lon sewi.',
      de: ['Ich bleibe ganz oben.'], en: ['I stay up top.'],
      lit: { de: 'ich · bleibe · an · Höhe', en: 'I · stay · at · above' } },

    { id: 'musi-30', kind: 'pona', sting: 1, tp: 'mi musi taso.',
      de: ['Ich mache nur Spaß.'], en: ['I am only playing.'],
      lit: { de: 'ich · spiele · nur', en: 'I · play · only' } },
    { id: 'musi-31', kind: 'pona', sting: 1, tp: 'sina pona tawa mi.',
      de: ['Ich mag dich.'], en: ['I like you.'],
      lit: { de: 'du · gut · für · mich', en: 'you · good · to · me' } },
    { id: 'musi-32', kind: 'pona', sting: 1, tp: 'mi olin e sina.',
      de: ['Ich hab dich lieb.'], en: ['I love you.'],
      lit: { de: 'ich · liebe · [Objekt] · dich', en: 'I · love · [object] · you' } },
    { id: 'musi-33', kind: 'pona', sting: 1, tp: 'mi wile ala e utala.',
      de: ['Ich will keinen Streit.'], en: ['I do not want a fight.'],
      lit: { de: 'ich · will · nicht · [Objekt] · Kampf',
             en: 'I · want · not · [object] · fight' } },
    { id: 'musi-34', kind: 'pona', sting: 1, tp: 'mi pakala.',
      de: ['Mein Fehler.'], en: ['My mistake.'],
      lit: { de: 'ich · patze', en: 'I · blunder' } },
    { id: 'musi-35', kind: 'pona', sting: 1, tp: 'toki musi ni li pini.',
      de: ['Dieser Spaß ist vorbei.'], en: ['This joke is over.'],
      lit: { de: 'Rede · lustig · diese · ist · zu Ende',
             en: 'talk · funny · this · is · finished' } },
  ],

  // Bausätze: aus jeder Kombination entsteht ein neuer, grammatisch geprüfter
  // Satz. Das ist der eigentliche Lerneffekt — ein Muster, viele Füllungen.
  patterns: [
    {
      id: 'p1',
      frame: '{a} sina li {b}.',
      name: { de: 'Dein X ist Y', en: 'Your X is Y' },
      say: { de: (a, b) => `Dein ${a} ist ${b}.`, en: (a, b) => `Your ${a} is ${b}.` },
      slots: [
        [['lawa', 'Kopf', 'head'], ['oko', 'Auge', 'eye'], ['uta', 'Mund', 'mouth'],
         ['luka', 'Arm', 'arm'], ['noka', 'Bein', 'leg'], ['monsi', 'Hintern', 'behind'],
         ['kon', 'Geruch', 'smell'], ['toki', 'Gerede', 'talk'], ['nimi', 'Name', 'name'],
         ['tomo', 'Zuhause', 'home'], ['moku', 'Essen', 'food'], ['len', 'Klamotte', 'clothing'],
         ['kalama', 'Krach', 'noise'], ['sitelen', 'Bild', 'picture']],
        [['jaki', 'eklig', 'gross'], ['ike', 'mies', 'bad'], ['lili', 'winzig', 'tiny'],
         ['nasa', 'wirr', 'strange'], ['pakala', 'kaputt', 'broken'], ['suli', 'riesig', 'huge'],
         ['mute', 'zu viel', 'too much'], ['pimeja', 'dunkel', 'dark'],
         ['lete', 'kalt', 'cold'], ['sin', 'neumodisch', 'newfangled']],
      ],
    },
    {
      id: 'p2',
      frame: 'sina {a} e {b}.',
      name: { de: 'Du tust X', en: 'You do X' },
      say: { de: (a, b) => `Du ${a} ${b}.`, en: (a, b) => `You ${a} ${b}.` },
      slots: [
        [['moku', 'isst', 'eat'], ['pana', 'verteilst', 'hand out'], ['lukin', 'begaffst', 'stare at'],
         ['jo', 'hortest', 'hoard'], ['kama', 'holst', 'bring'], ['awen', 'hältst fest an', 'cling to'],
         ['toki', 'redest von', 'talk about'], ['pali', 'baust', 'build']],
        [['jaki', 'Dreck', 'filth'], ['kon', 'Luft', 'air'], ['ijo nasa', 'wirres Zeug', 'strange stuff'],
         ['moku pakala', 'verdorbenes Essen', 'spoiled food'], ['nimi ike', 'böse Worte', 'bad words'],
         ['telo jaki', 'Schmutzwasser', 'dirty water'], ['lipu lili', 'kleine Zettel', 'little notes'],
         ['tomo lili', 'ein winziges Haus', 'a tiny house']],
      ],
    },
    {
      id: 'p3',
      frame: 'sina jan pi {a}.',
      name: { de: 'Du bist ein Mensch von …', en: 'You are a person of …' },
      say: { de: (a) => `Du bist ein Mensch ${a}.`, en: (a) => `You are a person ${a}.` },
      slots: [
        [['sona ala', 'ohne Ahnung', 'without a clue'], ['toki mute', 'des Vielredens', 'of much talking'],
         ['pali ala', 'des Nichtstuns', 'of no work'], ['lape suli', 'des langen Schlafs', 'of long sleep'],
         ['moku mute', 'der großen Portionen', 'of big helpings'],
         ['kalama ike', 'des üblen Krachs', 'of ugly noise'],
         ['sona lili', 'mit wenig Wissen', 'of little knowledge']],
      ],
    },
  ],
};

if (typeof module !== 'undefined') { module.exports = TOKIPONA_MUSI; }
