// Offene Aufgaben: eine Frage auf toki pona, eine freie Antwort.
//
// Hier gibt es keine Musterlösung zum Abgleichen. Geprüft wird, was der
// Parser prüfen kann: Ist der Satz grammatisch, und trägt er das, wonach
// gefragt war — ein Objekt mit e, ein Ziel nach der Präposition, ein
// la-Vorfeld. Alles andere ist frei. Die Beispiele stehen erst danach da,
// als Vergleich, nicht als Vorgabe.
const TOKIPONA_TOKI = {
  // Beschriftung der geforderten Satzteile (die Rollen kommen aus dem Röntgen)
  needs: {
    object: { de: 'ein Objekt mit <b>e</b>', en: 'an object with <b>e</b>' },
    complement: { de: 'ein Ziel hinter der Präposition', en: 'a target after the preposition' },
    context: { de: 'ein Vorfeld mit <b>la</b>', en: 'a context with <b>la</b>' },
    subject: { de: 'ein Subjekt', en: 'a subject' },
    preverb: { de: 'ein Präverb wie <b>wile</b> oder <b>ken</b>', en: 'a preverb such as <b>wile</b> or <b>ken</b>' },
  },

  prompts: [
    { id: 'q01', stage: 1, tp: 'sina pona ala pona?',
      de: ['Geht es dir gut?'], en: ['Are you well?'], need: [],
      models: ['mi pona.', 'mi pona ala.', 'mi lape wile.'] },
    { id: 'q02', stage: 2, tp: 'sina jan seme?',
      de: ['Was für ein Mensch bist du?'], en: ['What kind of person are you?'], need: [],
      models: ['mi jan pona.', 'mi jan pi toki pona.', 'mi jan lili.'] },
    { id: 'q03', stage: 3, tp: 'sina moku e seme?',
      de: ['Was isst du?'], en: ['What do you eat?'], need: ['object'],
      models: ['mi moku e kili.', 'mi moku e telo.', 'mi moku e pan.'] },
    { id: 'q04', stage: 3, tp: 'sina lukin e seme?',
      de: ['Was siehst du?'], en: ['What do you see?'], need: ['object'],
      models: ['mi lukin e lipu.', 'mi lukin e soweli suli.'] },
    { id: 'q05', stage: 4, tp: 'sina pali e seme?',
      de: ['Was machst du?'], en: ['What are you making?'], need: ['object'],
      models: ['mi pali e tomo.', 'mi pali e moku pona.'] },
    { id: 'q06', stage: 5, tp: 'ijo seme li pona tawa sina?',
      de: ['Was magst du?'], en: ['What do you like?'], need: ['subject'],
      models: ['soweli li pona tawa mi.', 'kasi li pona tawa mi.', 'toki pona li pona tawa mi.'] },
    { id: 'q07', stage: 6, tp: 'sina lon seme?',
      de: ['Wo bist du?'], en: ['Where are you?'], need: ['complement'],
      models: ['mi lon tomo.', 'mi lon ma tomo.', 'mi lon poka pi jan pona mi.'] },
    { id: 'q08', stage: 6, tp: 'sina tawa seme?',
      de: ['Wohin gehst du?'], en: ['Where are you going?'], need: ['complement'],
      models: ['mi tawa tomo moku.', 'mi tawa ma ante.'] },
    { id: 'q09', stage: 7, tp: 'nimi sina li seme?',
      de: ['Wie heißt du?'], en: ['What is your name?'], need: [],
      models: ['mi jan Ana.', 'nimi mi li jan Mose.'] },
    { id: 'q10', stage: 7, tp: 'o toki e ijo pona!',
      de: ['Sag etwas Nettes!'], en: ['Say something kind!'], need: [],
      models: ['sina pona tawa mi.', 'tenpo sina li pona.'] },
    { id: 'q11', stage: 8, tp: 'kule seme li pona tawa sina?',
      de: ['Welche Farbe magst du?'], en: ['Which colour do you like?'], need: ['subject'],
      models: ['kule laso li pona tawa mi.', 'kule loje li pona tawa mi.'] },
    { id: 'q12', stage: 9, tp: 'tenpo pini la sina pali e seme?',
      de: ['Was hast du gemacht?'], en: ['What did you do?'], need: ['context', 'object'],
      models: ['tenpo pini la mi pali e lipu.', 'tenpo pini la mi moku e kili.'] },
    { id: 'q13', stage: 9, tp: 'sina jan pi pali seme?',
      de: ['Was für Arbeit machst du?'], en: ['What kind of work do you do?'], need: [],
      models: ['mi jan pi pali lipu.', 'mi jan pi pana sona.'] },
    { id: 'q14', stage: 10, tp: 'sina wile pali e seme?',
      de: ['Was willst du machen?'], en: ['What do you want to do?'], need: ['preverb', 'object'],
      models: ['mi wile pali e tomo.', 'mi wile moku e pan.'] },
    { id: 'q15', stage: 10, tp: 'tenpo kama la sina tawa seme?',
      de: ['Wohin gehst du demnächst?'], en: ['Where will you go?'], need: ['context', 'complement'],
      models: ['tenpo kama la mi tawa ma ante.', 'tenpo kama la mi tawa tomo pi jan pona mi.'] },
    { id: 'q16', stage: 11, tp: 'sina jo e ijo mute anu ijo lili?',
      de: ['Hast du viel oder wenig?'], en: ['Do you have much or little?'], need: ['object'],
      models: ['mi jo e ijo lili.', 'mi jo e lipu tu.'] },
  ],

  // Wörter, die in keiner Kursaufgabe vorkommen, brauchen trotzdem einen
  // Beispielsatz in der Wortliste.
  extras: {
    anu: { tp: 'sina moku e kili anu telo?', de: 'Isst du Obst oder Wasser?',
           en: 'Do you consume fruit or water?' },
    en: { tp: 'mi en sina li pona.', de: 'Du und ich sind gut.', en: 'You and I are good.' },
    ko: { tp: 'ko li lon noka mi.', de: 'Matsch ist an meinem Fuß.', en: 'Goo is on my foot.' },
    len: { tp: 'len mi li laso.', de: 'Meine Kleidung ist blau.', en: 'My clothing is blue.' },
    mani: { tp: 'mi jo e mani lili.', de: 'Ich habe wenig Geld.', en: 'I have little money.' },
    mu: { tp: 'soweli li mu.', de: 'Das Tier macht Tierlaute.', en: 'The animal makes animal noise.' },
    noka: { tp: 'noka mi li wawa.', de: 'Meine Beine sind stark.', en: 'My legs are strong.' },
    palisa: { tp: 'palisa li kiwen.', de: 'Der Stock ist hart.', en: 'The stick is hard.' },
    poki: { tp: 'moku li lon poki.', de: 'Das Essen ist in der Schüssel.',
            en: 'The food is in the container.' },
    selo: { tp: 'selo kili li loje.', de: 'Die Schale der Frucht ist rot.',
            en: 'The skin of the fruit is red.' },
    sin: { tp: 'mi jo e lipu sin.', de: 'Ich habe ein neues Buch.', en: 'I have a new book.' },
    unpa: { tp: 'jan tu li unpa.', de: 'Zwei Menschen haben Sex.', en: 'Two people have sex.' },
    waso: { tp: 'waso li tawa sewi.', de: 'Der Vogel fliegt nach oben.', en: 'The bird goes upward.' },
    epiku: { tp: 'musi ni li epiku.', de: 'Dieses Spiel ist episch.', en: 'This game is epic.' },
    jasima: { tp: 'mi lukin e jasima.', de: 'Ich schaue in den Spiegel.',
              en: 'I look into the mirror.' },
    kijetesantakalu: { tp: 'kijetesantakalu li soweli pona.',
                       de: 'Der Waschbär ist ein nettes Tier.', en: 'The raccoon is a fine animal.' },
    kin: { tp: 'mi kin li tawa.', de: 'Ich gehe auch.', en: 'I am going too.' },
    kipisi: { tp: 'mi kipisi e pan.', de: 'Ich schneide das Brot.', en: 'I cut the bread.' },
    kokosila: { tp: 'o kokosila ala!', de: 'Sprich hier nicht die andere Sprache!',
                en: 'Do not speak the other language here!' },
    ku: { tp: 'lipu ku li suli.', de: 'Das ku-Buch ist dick.', en: 'The ku book is thick.' },
    lanpan: { tp: 'jan li lanpan e mani mi.', de: 'Jemand nimmt mir das Geld weg.',
              en: 'Someone takes my money.' },
    leko: { tp: 'leko li lon supa.', de: 'Der Klotz liegt auf dem Tisch.',
            en: 'The block is on the table.' },
    meso: { tp: 'moku ni li meso.', de: 'Dieses Essen ist mittelmäßig.', en: 'This food is mediocre.' },
    misikeke: { tp: 'mi moku e misikeke.', de: 'Ich nehme Medizin.', en: 'I take medicine.' },
    monsuta: { tp: 'monsuta li lon tomo pimeja.', de: 'Ein Monster ist im dunklen Haus.',
               en: 'A monster is in the dark house.' },
    namako: { tp: 'mi pana e namako tawa moku.', de: 'Ich gebe Gewürz ans Essen.',
              en: 'I add spice to the food.' },
    oko: { tp: 'oko mi li lape.', de: 'Meine Augen schlafen.', en: 'My eyes are asleep.' },
    soko: { tp: 'soko li lon ma kasi.', de: 'Der Pilz ist im Wald.', en: 'The mushroom is in the forest.' },
    tonsi: { tp: 'jan tonsi li pona.', de: 'Die nichtbinäre Person ist gut.',
             en: 'The nonbinary person is good.' },
    n: { tp: 'n. mi wile lukin.', de: 'Hm. Ich will nachsehen.', en: 'Hm. I want to look.' },
  },

  // Zwei kurze Gedanken, ein Satz. Genau die Stelle, an der es hakt: „la“
  // stellt einen Rahmen voran, „pi“ gruppiert eine mehrwortige Beifügung um.
  joins: [
    { id: 'j01', stage: 9, kind: 'la', parts: ['tenpo pini', 'mi moku e kili'],
      tp: 'tenpo pini la mi moku e kili.',
      de: ['Früher habe ich Obst gegessen.'], en: ['Earlier I ate fruit.'] },
    { id: 'j02', stage: 9, kind: 'la', parts: ['tenpo suno ni', 'mi pali mute'],
      tp: 'tenpo suno ni la mi pali mute.',
      de: ['Heute arbeite ich viel.'], en: ['Today I work a lot.'] },
    { id: 'j03', stage: 9, kind: 'la', parts: ['sina lape', 'sina wawa'],
      tp: 'sina lape la sina wawa.',
      de: ['Wenn du schläfst, bist du stark.'], en: ['If you sleep, you are strong.'] },
    { id: 'j04', stage: 9, kind: 'la', parts: ['ma li lete', 'mi awen lon tomo'],
      tp: 'ma li lete la mi awen lon tomo.',
      de: ['Wenn es draußen kalt ist, bleibe ich zu Hause.'],
      en: ['When it is cold outside, I stay at home.'] },
    { id: 'j05', stage: 9, kind: 'la', parts: ['tenpo kama', 'mi kama sona e toki pona'],
      tp: 'tenpo kama la mi kama sona e toki pona.',
      de: ['Bald lerne ich toki pona.'], en: ['Soon I will learn toki pona.'] },
    { id: 'j06', stage: 9, kind: 'pi', parts: ['jan', 'toki pona'],
      tp: 'jan pi toki pona li toki.',
      de: ['Der toki-pona-Sprecher redet.'], en: ['The toki pona speaker is talking.'] },
    { id: 'j07', stage: 9, kind: 'pi', parts: ['tomo', 'pali mute'],
      tp: 'tomo pi pali mute li suli.',
      de: ['Das Haus der vielen Arbeit ist groß.'], en: ['The house of much work is big.'] },
    { id: 'j08', stage: 9, kind: 'pi', parts: ['jan', 'pana sona'],
      tp: 'jan pi pana sona li pona.',
      de: ['Die Lehrerin ist gut.'], en: ['The teacher is good.'] },
    { id: 'j09', stage: 9, kind: 'pi', parts: ['lipu', 'toki mute'],
      tp: 'mi lukin e lipu pi toki mute.',
      de: ['Ich lese ein Buch mit vielen Sprachen.'], en: ['I read a book of many languages.'] },
    { id: 'j10', stage: 10, kind: 'la', parts: ['mi wile lape', 'mi tawa tomo mi'],
      tp: 'mi wile lape la mi tawa tomo mi.',
      de: ['Wenn ich schlafen will, gehe ich nach Hause.'],
      en: ['When I want to sleep, I go home.'] },
  ],
};

if (typeof module !== 'undefined') { module.exports = TOKIPONA_TOKI; }
