// Offene Aufgaben: eine Frage auf toki pona, eine freie Antwort.
//
// Hier gibt es keine Musterlösung zum Abgleichen. Geprüft wird, was der
// Parser prüfen kann: Ist der Satz grammatisch, und trägt er das, wonach
// gefragt war — ein Objekt mit e, ein Ziel nach der Präposition, ein
// la-Vorfeld. Alles andere ist frei. Die Beispiele stehen erst danach da,
// als Vergleich, nicht als Vorgabe.
const TOKIPONA_TOKI = {
  // Beschriftung der geforderten Satzteile (die Rollen kommen aus dem Röntgen)
  needs: {
    object: { de: 'ein Objekt mit <b>e</b>', en: 'an object with <b>e</b>' },
    complement: { de: 'ein Ziel hinter der Präposition', en: 'a target after the preposition' },
    context: { de: 'ein Vorfeld mit <b>la</b>', en: 'a context with <b>la</b>' },
    subject: { de: 'ein Subjekt', en: 'a subject' },
    preverb: { de: 'ein Präverb wie <b>wile</b> oder <b>ken</b>', en: 'a preverb such as <b>wile</b> or <b>ken</b>' },
  },

  // ---------------------------------------------------------- Lektion 0
  //
  // Der Kurs fängt bei den Wörtern an — hier fängt er beim Satz an. Vier
  // Regeln, jede mit einem Beispiel, einem Gegenbeispiel und danach zwei
  // Aufgaben, die genau sie brauchen.
  //
  // Die Gegenbeispiele sind von zweierlei Art, und der Unterschied ist der
  // halbe Lerninhalt: `falsch` verletzt eine Regel — der Parser weist es ab.
  // `anders` ist tadellose Sprache und heißt nur etwas anderes; genau daran
  // sieht man, was li und e eigentlich tun. prototype/test.js prüft beides.
  nasin: {
    title: { de: 'Wie ein Satz gebaut ist', en: 'How a sentence is built' },
    note: {
      de: 'Zwei kleine Wörter tragen den ganzen Satzbau: <b>li</b> trennt '
        + 'Subjekt und Prädikat, <b>e</b> kündigt das Objekt an. Ab jetzt siehst '
        + 'du beide in jedem Satz.',
      en: 'Two little words carry the whole structure: <b>li</b> separates '
        + 'subject and predicate, <b>e</b> announces the object. From here on you '
        + 'will see both in every sentence.',
    },
    words: ['mi', 'sina', 'ona', 'jan', 'soweli', 'li', 'e',
            'pona', 'moku', 'lukin', 'kili', 'telo', 'lape'],

    rules: [
      { id: 'r1', tp: 'soweli li pona.',
        de: 'Das Tier ist gut.', en: 'The animal is good.',
        concepts: ['c_li'],
        point: {
          de: 'Ein Satz hat zwei Teile: wovon die Rede ist, und was darüber '
            + 'gesagt wird. Dazwischen steht <b>li</b>. Es ist kein Wort mit '
            + 'Bedeutung, sondern die Naht.',
          en: 'A sentence has two parts: what is being talked about, and what is '
            + 'said about it. Between them stands <b>li</b>. It carries no meaning '
            + 'of its own — it is the seam.',
        },
        bad: { kind: 'anders', tp: 'soweli pona.',
               de: 'Auch richtige Sprache — nur kein Satz. Ohne <b>li</b> wird '
                 + '<i>pona</i> zur Beifügung: „ein gutes Tier“.',
               en: 'Perfectly good language — just not a sentence. Without '
                 + '<b>li</b>, <i>pona</i> becomes a modifier: “a good animal”.' } },

      { id: 'r2', tp: 'mi pona.',
        de: 'Mir geht es gut.', en: 'I am well.',
        concepts: ['c_li', 'c_mi_sina'],
        point: {
          de: 'Eine Ausnahme, und nur diese eine: steht <b>mi</b> oder <b>sina</b> '
            + 'allein als Subjekt, fällt <b>li</b> weg. Kommt noch ein Wort dazu — '
            + '<i>mi mute li pona</i> —, steht es wieder da.',
          en: 'One exception, and only this one: when <b>mi</b> or <b>sina</b> '
            + 'stands alone as the subject, <b>li</b> drops out. Add another word — '
            + '<i>mi mute li pona</i> — and it is back.',
        },
        bad: { kind: 'falsch', tp: 'mi li pona.',
               de: 'Nach <b>mi</b> allein steht nie <b>li</b>.',
               en: 'After <b>mi</b> alone there is never a <b>li</b>.' } },

      { id: 'r3', tp: 'soweli li moku e kili.',
        de: 'Das Tier isst eine Frucht.', en: 'The animal eats a fruit.',
        concepts: ['c_e_objekt'],
        point: {
          de: 'Was wird gegessen? Das sagt <b>e</b>. Es steht vor dem Objekt und '
            + 'gehört ihm — ohne <b>e</b> gibt es kein Objekt, egal wie die Wörter '
            + 'stehen.',
          en: 'What is being eaten? <b>e</b> says so. It stands before the object '
            + 'and belongs to it — without <b>e</b> there is no object, no matter '
            + 'how the words are arranged.',
        },
        bad: { kind: 'anders', tp: 'soweli li moku kili.',
               de: 'Ein sauberer Satz — er sagt nur nicht, <i>was</i> gegessen '
                 + 'wird. Ohne <b>e</b> beschreibt <i>kili</i> nur das <i>moku</i>: '
                 + 'etwa „isst auf Frucht-Art“.',
               en: 'A sound sentence — it just never says <i>what</i> is eaten. '
                 + 'Without <b>e</b>, <i>kili</i> only describes the <i>moku</i>: '
                 + 'something like “eats fruit-wise”.' } },

      { id: 'r4', tp: 'mi lukin e sina.',
        de: 'Ich sehe dich.', en: 'I see you.',
        concepts: ['c_li', 'c_e_objekt'],
        point: {
          de: 'Beide Regeln zusammen: nach <b>mi</b> allein kein <b>li</b>, vor dem '
            + 'Objekt aber sehr wohl <b>e</b>. Die Reihenfolge liegt fest — '
            + 'Subjekt, <b>li</b>, Prädikat, <b>e</b>, Objekt.',
          en: 'Both rules at once: no <b>li</b> after <b>mi</b> alone, but <b>e</b> '
            + 'before the object all the same. The order is fixed — subject, '
            + '<b>li</b>, predicate, <b>e</b>, object.',
        },
        bad: { kind: 'falsch', tp: 'mi li lukin e sina.',
               de: 'Das <b>li</b> ist zu viel, das <b>e</b> nicht.',
               en: 'The <b>li</b> is one too many; the <b>e</b> is not.' } },
    ],

    items: [
      { id: 'n01', rule: 'r1', direction: 'tp_de', tp: 'jan li pona.',
        de: ['Der Mensch ist gut.'], en: ['The person is good.'] },
      { id: 'n02', rule: 'r1', direction: 'de_tp', tp: 'soweli li lape.',
        de: ['Das Tier schläft.'], en: ['The animal sleeps.'] },
      { id: 'n03', rule: 'r1', direction: 'de_tp', tp: 'ona li moku.',
        de: ['Sie isst.'], en: ['She eats.'] },

      { id: 'n04', rule: 'r2', direction: 'tp_de', tp: 'sina lukin.',
        de: ['Du siehst.'], en: ['You see.'] },
      { id: 'n05', rule: 'r2', direction: 'de_tp', tp: 'mi lape.',
        de: ['Ich schlafe.'], en: ['I sleep.'] },
      { id: 'n06', rule: 'r2', direction: 'de_tp', tp: 'sina pona.',
        de: ['Dir geht es gut.'], en: ['You are well.'] },

      { id: 'n07', rule: 'r3', direction: 'tp_de', tp: 'jan li moku e telo.',
        de: ['Der Mensch trinkt Wasser.'], en: ['The person drinks water.'] },
      { id: 'n08', rule: 'r3', direction: 'de_tp', tp: 'soweli li lukin e kili.',
        de: ['Das Tier sieht eine Frucht.'], en: ['The animal sees a fruit.'] },
      { id: 'n09', rule: 'r3', direction: 'de_tp', tp: 'ona li moku e kili.',
        de: ['Sie isst eine Frucht.'], en: ['She eats a fruit.'] },

      { id: 'n10', rule: 'r4', direction: 'tp_de', tp: 'mi moku e telo.',
        de: ['Ich trinke Wasser.'], en: ['I drink water.'] },
      { id: 'n11', rule: 'r4', direction: 'de_tp', tp: 'sina lukin e soweli.',
        de: ['Du siehst das Tier.'], en: ['You see the animal.'] },
      { id: 'n12', rule: 'r4', direction: 'de_tp', tp: 'mi lukin e jan.',
        de: ['Ich sehe den Menschen.'], en: ['I see the person.'] },
    ],
  },

  prompts: [
    { id: 'q01', stage: 1, tp: 'sina pona ala pona?',
      de: ['Geht es dir gut?'], en: ['Are you well?'], need: [],
      models: ['mi pona.', 'mi pona ala.', 'mi lape wile.'] },
    { id: 'q02', stage: 2, tp: 'sina jan seme?',
      de: ['Was für ein Mensch bist du?'], en: ['What kind of person are you?'], need: [],
      models: ['mi jan pona.', 'mi jan pi toki pona.', 'mi jan lili.'] },
    { id: 'q03', stage: 3, tp: 'sina moku e seme?',
      de: ['Was isst du?'], en: ['What do you eat?'], need: ['object'],
      models: ['mi moku e kili.', 'mi moku e telo.', 'mi moku e pan.'] },
    { id: 'q04', stage: 3, tp: 'sina lukin e seme?',
      de: ['Was siehst du?'], en: ['What do you see?'], need: ['object'],
      models: ['mi lukin e lipu.', 'mi lukin e soweli suli.'] },
    { id: 'q05', stage: 4, tp: 'sina pali e seme?',
      de: ['Was machst du?'], en: ['What are you making?'], need: ['object'],
      models: ['mi pali e tomo.', 'mi pali e moku pona.'] },
    { id: 'q06', stage: 5, tp: 'ijo seme li pona tawa sina?',
      de: ['Was magst du?'], en: ['What do you like?'], need: ['subject'],
      models: ['soweli li pona tawa mi.', 'kasi li pona tawa mi.', 'toki pona li pona tawa mi.'] },
    { id: 'q07', stage: 6, tp: 'sina lon seme?',
      de: ['Wo bist du?'], en: ['Where are you?'], need: ['complement'],
      models: ['mi lon tomo.', 'mi lon ma tomo.', 'mi lon poka pi jan pona mi.'] },
    { id: 'q08', stage: 6, tp: 'sina tawa seme?',
      de: ['Wohin gehst du?'], en: ['Where are you going?'], need: ['complement'],
      models: ['mi tawa tomo moku.', 'mi tawa ma ante.'] },
    { id: 'q09', stage: 7, tp: 'nimi sina li seme?',
      de: ['Wie heißt du?'], en: ['What is your name?'], need: [],
      models: ['mi jan Ana.', 'nimi mi li jan Mose.'] },
    { id: 'q10', stage: 7, tp: 'o toki e ijo pona!',
      de: ['Sag etwas Nettes!'], en: ['Say something kind!'], need: [],
      models: ['sina pona tawa mi.', 'tenpo sina li pona.'] },
    { id: 'q11', stage: 8, tp: 'kule seme li pona tawa sina?',
      de: ['Welche Farbe magst du?'], en: ['Which colour do you like?'], need: ['subject'],
      models: ['kule laso li pona tawa mi.', 'kule loje li pona tawa mi.'] },
    { id: 'q12', stage: 9, tp: 'tenpo pini la sina pali e seme?',
      de: ['Was hast du gemacht?'], en: ['What did you do?'], need: ['context', 'object'],
      models: ['tenpo pini la mi pali e lipu.', 'tenpo pini la mi moku e kili.'] },
    { id: 'q13', stage: 9, tp: 'sina jan pi pali seme?',
      de: ['Was für Arbeit machst du?'], en: ['What kind of work do you do?'], need: [],
      models: ['mi jan pi pali lipu.', 'mi jan pi pana sona.'] },
    { id: 'q14', stage: 10, tp: 'sina wile pali e seme?',
      de: ['Was willst du machen?'], en: ['What do you want to do?'], need: ['preverb', 'object'],
      models: ['mi wile pali e tomo.', 'mi wile moku e pan.'] },
    { id: 'q15', stage: 10, tp: 'tenpo kama la sina tawa seme?',
      de: ['Wohin gehst du demnächst?'], en: ['Where will you go?'], need: ['context', 'complement'],
      models: ['tenpo kama la mi tawa ma ante.', 'tenpo kama la mi tawa tomo pi jan pona mi.'] },
    { id: 'q16', stage: 11, tp: 'sina jo e ijo mute anu ijo lili?',
      de: ['Hast du viel oder wenig?'], en: ['Do you have much or little?'], need: ['object'],
      models: ['mi jo e ijo lili.', 'mi jo e lipu tu.'] },
  ],

  // Sätze für draußen: was man wirklich sagt. Gruppiert nach Gelegenheit,
  // jede Zeile mit wörtlicher Lesart — bei 137 Wörtern ist die halbe Miete,
  // zu sehen, wie umschrieben wird.
  phrases: [
    {
      id: 'open', name: { de: 'Hallo und Tschüss', en: 'Hello and goodbye' },
      lines: [
        { id: 'p01', tp: 'toki!', de: 'Hallo!', en: 'Hi!',
          lit: { de: 'Sprache!', en: 'language!' } },
        { id: 'p02', tp: 'toki a!', de: 'Hallöchen!', en: 'Hey there!',
          lit: { de: 'Sprache · [Ausruf]', en: 'language · [exclamation]' } },
        { id: 'p03', tp: 'mi tawa.', de: 'Ich geh dann mal. (Tschüss)', en: 'I am off. (bye)',
          lit: { de: 'ich · gehe', en: 'I · go' } },
        { id: 'p04', tp: 'tawa pona!', de: 'Mach’s gut!', en: 'Safe travels!',
          lit: { de: 'Gehen · gut', en: 'going · good' } },
        { id: 'p05', tp: 'o kama pona!', de: 'Willkommen!', en: 'Welcome!',
          lit: { de: '[Befehl] · komm · gut', en: '[command] · come · well' } },
        { id: 'p06', tp: 'lape pona!', de: 'Schlaf gut!', en: 'Sleep well!',
          lit: { de: 'Schlaf · gut', en: 'sleep · good' } },
        { id: 'p07', tp: 'suno pona!', de: 'Guten Tag!', en: 'Good day!',
          lit: { de: 'Sonne · gut', en: 'sun · good' } },
        { id: 'p08', tp: 'sina pona ala pona?', de: 'Geht’s dir gut?', en: 'Are you well?',
          lit: { de: 'du · gut · nicht · gut', en: 'you · good · not · good' } },
      ],
    },
    {
      id: 'pona', name: { de: 'Höflichkeit', en: 'Courtesy' },
      lines: [
        { id: 'p09', tp: 'pona!', de: 'Danke!', en: 'Thanks!',
          lit: { de: 'gut', en: 'good' } },
        { id: 'p10', tp: 'pona tawa sina.', de: 'Danke dir.', en: 'Thanks to you.',
          lit: { de: 'Gutes · zu · dir', en: 'good · to · you' } },
        { id: 'p11', tp: 'mi pakala.', de: 'Sorry, mein Fehler.', en: 'Sorry, my mistake.',
          lit: { de: 'ich · patze', en: 'I · blunder' } },
        { id: 'p12', tp: 'o awen lili.', de: 'Warte kurz.', en: 'Hold on a moment.',
          lit: { de: '[Befehl] · warte · wenig', en: '[command] · wait · little' } },
        { id: 'p13', tp: 'o pana e ni tawa mi.', de: 'Gib mir das bitte.',
          en: 'Please give me that.',
          lit: { de: '[Befehl] · gib · [Objekt] · das · zu · mir',
                 en: '[command] · give · [object] · this · to · me' } },
        { id: 'p14', tp: 'sina pona mute.', de: 'Du bist sehr nett.', en: 'You are very kind.',
          lit: { de: 'du · gut · sehr', en: 'you · good · very' } },
        { id: 'p15', tp: 'o toki sin.', de: 'Sag das nochmal.', en: 'Say that again.',
          lit: { de: '[Befehl] · sprich · neu', en: '[command] · speak · anew' } },
        { id: 'p16', tp: 'mi sona ala.', de: 'Ich weiß es nicht.', en: 'I do not know.',
          lit: { de: 'ich · weiß · nicht', en: 'I · know · not' } },
      ],
    },
    {
      id: 'kama', name: { de: 'Kennenlernen', en: 'Getting to know' },
      lines: [
        { id: 'p17', tp: 'nimi sina li seme?', de: 'Wie heißt du?', en: 'What is your name?',
          lit: { de: 'Name · dein · ist · was', en: 'name · your · is · what' } },
        { id: 'p18', tp: 'mi jan Ana.', de: 'Ich bin Ana.', en: 'I am Ana.',
          lit: { de: 'ich · Mensch · Ana', en: 'I · person · Ana' } },
        { id: 'p19', tp: 'sina tan ma seme?', de: 'Woher kommst du?', en: 'Where are you from?',
          lit: { de: 'du · von · Land · welchem', en: 'you · from · land · what' } },
        { id: 'p20', tp: 'mi tan ma Tosi.', de: 'Ich komme aus Deutschland.', en: 'I am from Germany.',
          lit: { de: 'ich · von · Land · Deutsch', en: 'I · from · land · German' } },
        { id: 'p21', tp: 'sina lon ma seme?', de: 'Wo bist du gerade?', en: 'Where are you?',
          lit: { de: 'du · an · Ort · welchem', en: 'you · at · place · what' } },
        { id: 'p22', tp: 'sina sona e toki seme?', de: 'Welche Sprachen kannst du?',
          en: 'Which languages do you know?',
          lit: { de: 'du · kennst · [Objekt] · Sprache · welche',
                 en: 'you · know · [object] · language · what' } },
        { id: 'p23', tp: 'mi kama sona e toki pona.', de: 'Ich lerne toki pona.',
          en: 'I am learning toki pona.',
          lit: { de: 'ich · komme · zu wissen · [Objekt] · toki pona',
                 en: 'I · come · to know · [object] · toki pona' } },
        { id: 'p24', tp: 'sina pali e seme lon tenpo suno ni?', de: 'Was machst du heute?',
          en: 'What are you doing today?',
          lit: { de: 'du · machst · was · an · Zeit · Sonne · dieser',
                 en: 'you · do · what · at · time · sun · this' } },
      ],
    },
    {
      id: 'moku', name: { de: 'Essen und Trinken', en: 'Food and drink' },
      lines: [
        { id: 'p25', tp: 'mi wile moku.', de: 'Ich habe Hunger.', en: 'I am hungry.',
          lit: { de: 'ich · will · essen', en: 'I · want · to eat' } },
        { id: 'p26', tp: 'mi wile e telo.', de: 'Ich habe Durst.', en: 'I am thirsty.',
          lit: { de: 'ich · will · [Objekt] · Wasser', en: 'I · want · [object] · water' } },
        { id: 'p27', tp: 'moku ni li pona mute!', de: 'Das schmeckt richtig gut!',
          en: 'This tastes great!',
          lit: { de: 'Essen · dieses · ist · gut · sehr', en: 'food · this · is · good · very' } },
        { id: 'p28', tp: 'mi moku ala e soweli.', de: 'Ich esse kein Fleisch.',
          en: 'I do not eat meat.',
          lit: { de: 'ich · esse · nicht · [Objekt] · Tier',
                 en: 'I · eat · not · [object] · animal' } },
        { id: 'p29', tp: 'o pana e telo tawa mi.', de: 'Bring mir bitte Wasser.',
          en: 'Please bring me water.',
          lit: { de: '[Befehl] · gib · [Objekt] · Wasser · zu · mir',
                 en: '[command] · give · [object] · water · to · me' } },
        { id: 'p30', tp: 'moku ni li seli mute.', de: 'Das ist sehr scharf.',
          en: 'This is very hot.',
          lit: { de: 'Essen · dieses · ist · heiß · sehr', en: 'food · this · is · hot · very' } },
        { id: 'p31', tp: 'mi pini moku.', de: 'Ich bin satt.', en: 'I am done eating.',
          lit: { de: 'ich · beende · essen', en: 'I · finish · eating' } },
        { id: 'p32', tp: 'esun li lon seme?', de: 'Wo ist der Laden?', en: 'Where is the shop?',
          lit: { de: 'Laden · ist · an · was', en: 'shop · is · at · what' } },
      ],
    },
    {
      id: 'tawa', name: { de: 'Unterwegs', en: 'Out and about' },
      lines: [
        { id: 'p33', tp: 'mi wile tawa ma tomo.', de: 'Ich will in die Stadt.',
          en: 'I want to go to town.',
          lit: { de: 'ich · will · gehen · Land · Haus', en: 'I · want · go · land · house' } },
        { id: 'p34', tp: 'nasin li lon seme?', de: 'Wo geht’s lang?', en: 'Which way is it?',
          lit: { de: 'Weg · ist · an · was', en: 'way · is · at · what' } },
        { id: 'p35', tp: 'o tawa poka mi.', de: 'Komm mit.', en: 'Come along with me.',
          lit: { de: '[Befehl] · geh · Seite · meine', en: '[command] · go · side · my' } },
        { id: 'p36', tp: 'mi sona ala e nasin.', de: 'Ich habe mich verlaufen.',
          en: 'I do not know the way.',
          lit: { de: 'ich · kenne · nicht · [Objekt] · Weg',
                 en: 'I · know · not · [object] · way' } },
        { id: 'p37', tp: 'tomo tawa li lon seme?', de: 'Wo ist das Auto?', en: 'Where is the car?',
          lit: { de: 'Haus · fahrend · ist · an · was', en: 'house · moving · is · at · what' } },
        { id: 'p38', tp: 'mi awen lon ni.', de: 'Ich bleibe hier.', en: 'I am staying here.',
          lit: { de: 'ich · bleibe · an · diesem', en: 'I · stay · at · this' } },
        { id: 'p39', tp: 'tenpo seme la sina kama?', de: 'Wann kommst du?',
          en: 'When are you coming?',
          lit: { de: 'Zeit · welche · [Rahmen] · du · kommst',
                 en: 'time · what · [frame] · you · come' } },
        { id: 'p40', tp: 'mi tawa lon tenpo kama.', de: 'Ich gehe später.', en: 'I will go later.',
          lit: { de: 'ich · gehe · an · Zeit · kommender',
                 en: 'I · go · at · time · coming' } },
      ],
    },
    {
      id: 'pilin', name: { de: 'Gefühle', en: 'Feelings' },
      lines: [
        { id: 'p41', tp: 'mi pilin pona.', de: 'Mir geht’s gut.', en: 'I feel good.',
          lit: { de: 'ich · fühle · gut', en: 'I · feel · good' } },
        { id: 'p42', tp: 'mi pilin ike.', de: 'Mir geht’s schlecht.', en: 'I feel bad.',
          lit: { de: 'ich · fühle · schlecht', en: 'I · feel · bad' } },
        { id: 'p43', tp: 'mi pilin monsuta.', de: 'Ich habe Angst.', en: 'I am scared.',
          lit: { de: 'ich · fühle · Monster', en: 'I · feel · monster' } },
        { id: 'p44', tp: 'mi wile lape.', de: 'Ich bin müde.', en: 'I am tired.',
          lit: { de: 'ich · will · schlafen', en: 'I · want · to sleep' } },
        { id: 'p45', tp: 'ni li pona tawa mi.', de: 'Das gefällt mir.', en: 'I like this.',
          lit: { de: 'dies · ist · gut · für · mich', en: 'this · is · good · to · me' } },
        { id: 'p46', tp: 'ni li ike tawa mi.', de: 'Das mag ich nicht.', en: 'I dislike this.',
          lit: { de: 'dies · ist · schlecht · für · mich', en: 'this · is · bad · to · me' } },
        { id: 'p47', tp: 'mi olin e sina.', de: 'Ich liebe dich.', en: 'I love you.',
          lit: { de: 'ich · liebe · [Objekt] · dich', en: 'I · love · [object] · you' } },
        { id: 'p48', tp: 'mi pilin nasa.', de: 'Mir ist komisch.', en: 'I feel strange.',
          lit: { de: 'ich · fühle · wirr', en: 'I · feel · strange' } },
      ],
    },
    {
      id: 'tenpo', name: { de: 'Zeit und Wetter', en: 'Time and weather' },
      lines: [
        { id: 'p49', tp: 'tenpo ni la seli li lon.', de: 'Gerade ist es warm.',
          en: 'Right now it is warm.',
          lit: { de: 'Zeit · diese · [Rahmen] · Wärme · ist · da',
                 en: 'time · this · [frame] · heat · is · present' } },
        { id: 'p50', tp: 'ma li lete.', de: 'Es ist kalt draußen.', en: 'It is cold outside.',
          lit: { de: 'Land · ist · kalt', en: 'land · is · cold' } },
        { id: 'p51', tp: 'telo li kama tan sewi.', de: 'Es regnet.', en: 'It is raining.',
          lit: { de: 'Wasser · kommt · von · oben', en: 'water · comes · from · above' } },
        { id: 'p52', tp: 'tenpo suno ni li pona.', de: 'Heute ist ein schöner Tag.',
          en: 'Today is a good day.',
          lit: { de: 'Zeit · Sonne · diese · ist · gut', en: 'time · sun · this · is · good' } },
        { id: 'p53', tp: 'tenpo pimeja li kama.', de: 'Es wird Nacht.', en: 'Night is coming.',
          lit: { de: 'Zeit · dunkle · kommt', en: 'time · dark · comes' } },
        { id: 'p54', tp: 'suno li lon sewi.', de: 'Die Sonne steht hoch.',
          en: 'The sun is high up.',
          lit: { de: 'Sonne · ist · an · Höhe', en: 'sun · is · at · above' } },
      ],
    },
    {
      id: 'ilo', name: { de: 'Geräte und Netz', en: 'Devices and net' },
      lines: [
        { id: 'p55', tp: 'ilo mi li pakala.', de: 'Mein Gerät ist kaputt.',
          en: 'My device is broken.',
          lit: { de: 'Gerät · mein · ist · kaputt', en: 'tool · my · is · broken' } },
        { id: 'p56', tp: 'ilo li jo ala e wawa.', de: 'Der Akku ist leer.',
          en: 'The battery is empty.',
          lit: { de: 'Gerät · hat · nicht · [Objekt] · Kraft',
                 en: 'tool · has · not · [object] · power' } },
        { id: 'p57', tp: 'mi lukin e sitelen tawa.', de: 'Ich schaue ein Video.',
          en: 'I am watching a video.',
          lit: { de: 'ich · sehe · [Objekt] · Bild · bewegtes',
                 en: 'I · look at · [object] · picture · moving' } },
        { id: 'p58', tp: 'o sitelen tawa mi.', de: 'Schreib mir.', en: 'Write to me.',
          lit: { de: '[Befehl] · schreib · zu · mir', en: '[command] · write · to · me' } },
        { id: 'p59', tp: 'lipu ni li pona.', de: 'Diese Seite ist gut.', en: 'This page is good.',
          lit: { de: 'Blatt · dieses · ist · gut', en: 'document · this · is · good' } },
        { id: 'p60', tp: 'mi toki kepeken ilo.', de: 'Ich telefoniere.',
          en: 'I am talking on a device.',
          lit: { de: 'ich · rede · mit · Gerät', en: 'I · speak · using · tool' } },
        { id: 'p61', tp: 'mi wile sona e nasin pi ilo ni.',
          de: 'Ich will wissen, wie dieses Gerät geht.',
          en: 'I want to know how this device works.',
          lit: { de: 'ich · will · wissen · [Objekt] · Weise · von · Gerät · diesem',
                 en: 'I · want · to know · [object] · way · of · tool · this' } },
      ],
    },
  ],

  // Mehrere Wege, dasselbe zu sagen — mit dem Unterschied dazwischen.
  // Beide Fassungen sind gültig; die Frage ist, was man meint.
  styles: [
    { id: 's01',
      topic: { de: 'mögen oder lieben', en: 'liking or loving' },
      ask: { de: 'Du willst sagen, dass dir Tiere gefallen — nicht, dass du sie liebst.',
             en: 'You want to say you like animals — not that you love them.' },
      right: 0,
      options: [
        { tp: 'soweli li pona tawa mi.',
          note: { de: 'wörtlich: Tiere sind gut für mich — das übliche „ich mag“.',
                  en: 'literally: animals are good to me — the usual way to say “I like”.' } },
        { tp: 'mi olin e soweli.',
          note: { de: 'olin ist die große Liebe, nicht der Geschmack.',
                  en: 'olin is deep love, not preference.' } },
      ] },
    { id: 's02',
      topic: { de: 'Zeit vorn oder hinten', en: 'time up front or at the back' },
      ask: { de: 'Der Zeitpunkt ist die Hauptsache: nachts, da schläfst du.',
             en: 'The time is the point: at night, that is when you sleep.' },
      right: 0,
      options: [
        { tp: 'tenpo pimeja la mi lape.',
          note: { de: 'la stellt den Rahmen voran und betont ihn.',
                  en: 'la fronts the frame and gives it weight.' } },
        { tp: 'mi lape lon tenpo pimeja.',
          note: { de: 'auch richtig, aber die Zeit ist hier nur Beiwerk.',
                  en: 'also correct, but here the time is just an aside.' } },
      ] },
    { id: 's03',
      topic: { de: 'pi oder ohne pi', en: 'pi or no pi' },
      ask: { de: 'Ein Haus für Bier — keine Aussage darüber, ob das Haus wirr ist.',
             en: 'A house for beer — not a claim that the house is strange.' },
      right: 0,
      options: [
        { tp: 'tomo pi telo nasa',
          note: { de: 'pi bündelt telo nasa zu einer Einheit: Haus des wirren Wassers.',
                  en: 'pi binds telo nasa into one unit: house of the strange water.' } },
        { tp: 'tomo telo nasa',
          note: { de: 'ohne pi wirken beide Wörter einzeln auf tomo: wirres Wasserhaus.',
                  en: 'without pi both words hit tomo separately: strange water house.' } },
      ] },
    { id: 's04',
      topic: { de: 'Menge oder Verstärkung', en: 'quantity or intensity' },
      ask: { de: 'Es sind viele Menschen — nicht ein besonders guter.',
             en: 'There are many people — not one especially good one.' },
      right: 0,
      options: [
        { tp: 'jan mute li pona.',
          note: { de: 'mute steht beim Menschen: viele Menschen.',
                  en: 'mute sits with the person: many people.' } },
        { tp: 'jan li pona mute.',
          note: { de: 'mute steht beim Gutsein: sehr gut.',
                  en: 'mute sits with the goodness: very good.' } },
      ] },
    { id: 's05',
      topic: { de: 'Bitte oder Bericht', en: 'request or report' },
      ask: { de: 'Du forderst jemanden auf zu essen.',
             en: 'You are telling someone to eat.' },
      right: 0,
      options: [
        { tp: 'o moku!',
          note: { de: 'o macht daraus Anrede und Aufforderung.',
                  en: 'o turns it into an address and a call to act.' } },
        { tp: 'sina moku.',
          note: { de: 'das ist eine Feststellung: du isst.',
                  en: 'that is a statement: you are eating.' } },
      ] },
    { id: 's06',
      topic: { de: 'Ja-Nein oder Was', en: 'yes-no or what' },
      ask: { de: 'Du fragst, ob das gut ist.', en: 'You are asking whether this is good.' },
      right: 0,
      options: [
        { tp: 'ni li pona ala pona?',
          note: { de: 'X ala X ist die Ja-Nein-Frage.', en: 'X ala X is the yes-no question.' } },
        { tp: 'ni li seme?',
          note: { de: 'seme fragt offen: was ist das?', en: 'seme asks openly: what is it?' } },
      ] },
    { id: 's07',
      topic: { de: 'mit Objekt oder ohne', en: 'with object or without' },
      ask: { de: 'Du sagst, was gegessen wird.', en: 'You say what is being eaten.' },
      right: 0,
      options: [
        { tp: 'mi moku e kili.',
          note: { de: 'e kündigt das Objekt an: ich esse Obst.',
                  en: 'e announces the object: I eat fruit.' } },
        { tp: 'mi moku.',
          note: { de: 'ohne e bleibt es beim Tun: ich esse.',
                  en: 'without e it stays at the doing: I am eating.' } },
      ] },
    { id: 's08',
      topic: { de: 'zeigen oder allgemein reden', en: 'pointing or speaking generally' },
      ask: { de: 'Du zeigst auf etwas Bestimmtes.', en: 'You are pointing at something specific.' },
      right: 0,
      options: [
        { tp: 'ni li pona.',
          note: { de: 'ni zeigt: das da ist gut.', en: 'ni points: that one is good.' } },
        { tp: 'ijo li pona.',
          note: { de: 'ijo ist irgendein Ding, ohne Zeigefinger.',
                  en: 'ijo is any thing at all, without pointing.' } },
      ] },
  ],

  // Wörter, die in keiner Kursaufgabe vorkommen, brauchen trotzdem einen
  // Beispielsatz in der Wortliste.
  extras: {
    anu: { tp: 'sina moku e kili anu telo?', de: 'Isst du Obst oder Wasser?',
           en: 'Do you consume fruit or water?' },
    en: { tp: 'mi en sina li pona.', de: 'Du und ich sind gut.', en: 'You and I are good.' },
    ko: { tp: 'ko li lon noka mi.', de: 'Matsch ist an meinem Fuß.', en: 'Goo is on my foot.' },
    len: { tp: 'len mi li laso.', de: 'Meine Kleidung ist blau.', en: 'My clothing is blue.' },
    mani: { tp: 'mi jo e mani lili.', de: 'Ich habe wenig Geld.', en: 'I have little money.' },
    mu: { tp: 'soweli li mu.', de: 'Das Tier macht Tierlaute.', en: 'The animal makes animal noise.' },
    noka: { tp: 'noka mi li wawa.', de: 'Meine Beine sind stark.', en: 'My legs are strong.' },
    palisa: { tp: 'palisa li kiwen.', de: 'Der Stock ist hart.', en: 'The stick is hard.' },
    poki: { tp: 'moku li lon poki.', de: 'Das Essen ist in der Schüssel.',
            en: 'The food is in the container.' },
    selo: { tp: 'selo kili li loje.', de: 'Die Schale der Frucht ist rot.',
            en: 'The skin of the fruit is red.' },
    sin: { tp: 'mi jo e lipu sin.', de: 'Ich habe ein neues Buch.', en: 'I have a new book.' },
    unpa: { tp: 'jan tu li unpa.', de: 'Zwei Menschen haben Sex.', en: 'Two people have sex.' },
    waso: { tp: 'waso li tawa sewi.', de: 'Der Vogel fliegt nach oben.', en: 'The bird goes upward.' },
    epiku: { tp: 'musi ni li epiku.', de: 'Dieses Spiel ist episch.', en: 'This game is epic.' },
    jasima: { tp: 'mi lukin e jasima.', de: 'Ich schaue in den Spiegel.',
              en: 'I look into the mirror.' },
    kijetesantakalu: { tp: 'kijetesantakalu li soweli pona.',
                       de: 'Der Waschbär ist ein nettes Tier.', en: 'The raccoon is a fine animal.' },
    kin: { tp: 'mi kin li tawa.', de: 'Ich gehe auch.', en: 'I am going too.' },
    kipisi: { tp: 'mi kipisi e pan.', de: 'Ich schneide das Brot.', en: 'I cut the bread.' },
    kokosila: { tp: 'o kokosila ala!', de: 'Sprich hier nicht die andere Sprache!',
                en: 'Do not speak the other language here!' },
    ku: { tp: 'lipu ku li suli.', de: 'Das ku-Buch ist dick.', en: 'The ku book is thick.' },
    lanpan: { tp: 'jan li lanpan e mani mi.', de: 'Jemand nimmt mir das Geld weg.',
              en: 'Someone takes my money.' },
    leko: { tp: 'leko li lon supa.', de: 'Der Klotz liegt auf dem Tisch.',
            en: 'The block is on the table.' },
    meso: { tp: 'moku ni li meso.', de: 'Dieses Essen ist mittelmäßig.', en: 'This food is mediocre.' },
    misikeke: { tp: 'mi moku e misikeke.', de: 'Ich nehme Medizin.', en: 'I take medicine.' },
    monsuta: { tp: 'monsuta li lon tomo pimeja.', de: 'Ein Monster ist im dunklen Haus.',
               en: 'A monster is in the dark house.' },
    namako: { tp: 'mi pana e namako tawa moku.', de: 'Ich gebe Gewürz ans Essen.',
              en: 'I add spice to the food.' },
    oko: { tp: 'oko mi li lape.', de: 'Meine Augen schlafen.', en: 'My eyes are asleep.' },
    soko: { tp: 'soko li lon ma kasi.', de: 'Der Pilz ist im Wald.', en: 'The mushroom is in the forest.' },
    tonsi: { tp: 'jan tonsi li pona.', de: 'Die nichtbinäre Person ist gut.',
             en: 'The nonbinary person is good.' },
    n: { tp: 'n. mi wile lukin.', de: 'Hm. Ich will nachsehen.', en: 'Hm. I want to look.' },
  },

  // Zwei kurze Gedanken, ein Satz. Genau die Stelle, an der es hakt: „la“
  // stellt einen Rahmen voran, „pi“ gruppiert eine mehrwortige Beifügung um.
  joins: [
    { id: 'j01', stage: 9, kind: 'la', parts: ['tenpo pini', 'mi moku e kili'],
      tp: 'tenpo pini la mi moku e kili.',
      de: ['Früher habe ich Obst gegessen.'], en: ['Earlier I ate fruit.'] },
    { id: 'j02', stage: 9, kind: 'la', parts: ['tenpo suno ni', 'mi pali mute'],
      tp: 'tenpo suno ni la mi pali mute.',
      de: ['Heute arbeite ich viel.'], en: ['Today I work a lot.'] },
    { id: 'j03', stage: 9, kind: 'la', parts: ['sina lape', 'sina wawa'],
      tp: 'sina lape la sina wawa.',
      de: ['Wenn du schläfst, bist du stark.'], en: ['If you sleep, you are strong.'] },
    { id: 'j04', stage: 9, kind: 'la', parts: ['ma li lete', 'mi awen lon tomo'],
      tp: 'ma li lete la mi awen lon tomo.',
      de: ['Wenn es draußen kalt ist, bleibe ich zu Hause.'],
      en: ['When it is cold outside, I stay at home.'] },
    { id: 'j05', stage: 9, kind: 'la', parts: ['tenpo kama', 'mi kama sona e toki pona'],
      tp: 'tenpo kama la mi kama sona e toki pona.',
      de: ['Bald lerne ich toki pona.'], en: ['Soon I will learn toki pona.'] },
    { id: 'j06', stage: 9, kind: 'pi', parts: ['jan', 'toki pona'],
      tp: 'jan pi toki pona li toki.',
      de: ['Der toki-pona-Sprecher redet.'], en: ['The toki pona speaker is talking.'] },
    { id: 'j07', stage: 9, kind: 'pi', parts: ['tomo', 'pali mute'],
      tp: 'tomo pi pali mute li suli.',
      de: ['Das Haus der vielen Arbeit ist groß.'], en: ['The house of much work is big.'] },
    { id: 'j08', stage: 9, kind: 'pi', parts: ['jan', 'pana sona'],
      tp: 'jan pi pana sona li pona.',
      de: ['Die Lehrerin ist gut.'], en: ['The teacher is good.'] },
    { id: 'j09', stage: 9, kind: 'pi', parts: ['lipu', 'toki mute'],
      tp: 'mi lukin e lipu pi toki mute.',
      de: ['Ich lese ein Buch mit vielen Sprachen.'], en: ['I read a book of many languages.'] },
    { id: 'j10', stage: 10, kind: 'la', parts: ['mi wile lape', 'mi tawa tomo mi'],
      tp: 'mi wile lape la mi tawa tomo mi.',
      de: ['Wenn ich schlafen will, gehe ich nach Hause.'],
      en: ['When I want to sleep, I go home.'] },
  ],
};

if (typeof module !== 'undefined') { module.exports = TOKIPONA_TOKI; }
